// R03 标准用词源（English）。纯常量、零 import：经 `npm run sync:contract` 原样复制到
// repos/orbit-app/src/api/copy/。术语和写法见
// docs/designs/redesign-2026-10/sprints/R03-copy-and-ja/{glossary,style-guide}.md；
// 改这里后在 repos/orbits 跑 `npm run copy:qa`，再到 App 跑 `npm run sync:contract`。键名与占位符三语一致（测试守着）。
// 设计稿原样搬运的句子注明出处 `01-system.html:<行>`。

export const en = {
  nav: {
    home: "Home",
    network: "Network",
    iorbit: "iOrbit",
    events: "Events",
    task: "Task",
    inbox: "Inbox",
    host: "Host",
    settings: "Settings",
    me: "Me",
    main: "Main navigation",
    back: "Back",
    backTo: "Back to {label}",
    askIorbit: "Ask iOrbit…",
  },
  taskSegments: {
    calendar: "Calendar",
    todo: "To-do",
    plan: "Plan",
    notes: "Notes",
  },
  action: {
    add: "Add",
    save: "Save",
    delete: "Delete",
    undo: "Undo",
    withdraw: "Withdraw",
    complete: "Mark done",
    edit: "Edit",
    cancel: "Cancel",
    close: "Close",
    retry: "Try again",
    open: "Open",
    later: "Later",
    notNow: "Not now",
    tomorrow: "Tomorrow",
    copy: "Copy",
    gotIt: "Got it",
  },
  chip: {
    overdue: "Overdue",
    failed: "Failed",
    limitReached: "Limit reached",
    today: "Today",
    tonight: "Tonight",
    daysLeft: "{count}d left",
    waitlist: "Waitlisted",
    estimated: "Estimated",
    draft: "Draft",
    waitingSync: "Waiting to sync",
    inReview: "Under host review",
    awaitingConfirmation: "Check needed",
    awaitingApproval: "Awaiting reply",
    confirmed: "Confirmed",
    completed: "Done",
    published: "Published",
    recommended: "Recommended",
    upcoming: "Upcoming",
    going: "Planning to go",
    registered: "Registered",
    notRegistered: "Not registered",
    followUp: "Needs follow-up",
    declineSuggested: "Consider skipping",
  },
  toast: {
    completed: "Marked as done",
    movedToTomorrow: "Moved to tomorrow",
    addedToTasks: "Added to tasks",
    saveFailed: "Couldn't save",
    savedOffline: "Saved offline",
    syncLater: "Will sync when you're online",
    copied: "Copied",
    deleted: "Deleted",
  },
  confirm: {
    deleteTitle: "Delete this {item}?",
    delete: "Delete",
    irreversible: "This can't be undone.",
  },
  filter: {
    clear: "Clear",
    showItems: "Show results ({count})",
    showPeople: "Show people ({count})",
    loosen: "Loosen filters",
  },
  aiCard: {
    why: "Based on: {reason}",
    showWhy: "Why this?",
    add: "Add",
    decline: "Not now",
    added: "Added",
    addFailed: "Couldn't add to {target}",
    nothingWritten: "Nothing was added.",
    reconnect: "Reconnect",
  },
  offline: {
    banner: "Offline · Changes will sync when you're online",
    pending: "To sync: {count}",
    synced: "Synced",
  },
  error: {
    loadFailed: "Couldn't load {item}",
    checkConnection: "Check your connection and try again.",
    inputKept: "What you typed hasn't been lost.",
    viewCached: "View saved copy",
    screenFailed: "Couldn't show this screen",
    screenFailedBody: "Your data hasn't been lost. Try again.",
    needsNetwork: "This screen needs an internet connection",
    needsNetworkBody: "Connect and try again.",
    signInRequired: "Please sign in",
    noAccess: "You don't have access to this screen",
  },
  degraded: {
    iorbitUnavailable: "iOrbit is temporarily unavailable",
    iorbitStopped: "Suggestions and drafts are paused. Tasks, calendar and notes still work as usual.",
  },
  loading: {
    loading: "Loading…",
    slow: "This is taking longer than usual",
  },
  sample: {
    banner: "Showing sample data · Numbers and people are fictional",
    tag: "Sample",
  },
  quota: {
    left: "This month: {count} left",
    reached: "Monthly limit reached",
  },
  push: {
    openTarget: "Open",
    remindInHour: "Remind me in 1 hour",
    markRead: "Mark as read in Inbox",
    fewerLikeThis: "Fewer notifications like this",
    openedFromPush: "Opened from a notification",
  },
  permission: {
    allowCamera: "Allow camera",
    allowNotifications: "Allow notifications",
    notNow: "Not now",
    openSettings: "Open Settings",
  },
  homeEdit: {
    edit: "Edit",
    done: "Done",
    comingSoon: "Coming soon",
  },
  draftBoundary: {
    create: "Create draft",
    open: "Open draft",
    copy: "Copy",
    openInMail: "Open in Mail",
    notice: "Orbit won't send it · You send it yourself",
    noMessage: "No message included · You can withdraw it later",
  },
} as const;
