// R03 标准用词源（简体中文）。纯常量、零 import：经 `npm run sync:contract` 原样复制到
// repos/orbit-app/src/api/copy/。术语和写法见
// docs/designs/redesign-2026-10/sprints/R03-copy-and-ja/{glossary,style-guide}.md；
// 改这里后在 repos/orbits 跑 `npm run copy:qa`，再到 App 跑 `npm run sync:contract`。键名与占位符三语一致（测试守着）。
// 设计稿原样搬运的句子注明出处 `01-system.html:<行>`。

export const zh = {
  nav: {
    home: "首页",
    network: "人脉",
    iorbit: "iOrbit",
    events: "活动",
    task: "Task",
    inbox: "收件箱",
    host: "主办",
    settings: "设置",
    me: "我的",
    main: "主导航",
    back: "返回",
    backTo: "返回{label}",
    askIorbit: "问 iOrbit…",
  },
  taskSegments: {
    calendar: "日历",
    todo: "待办",
    plan: "计划",
    notes: "笔记",
  },
  action: {
    add: "添加",
    save: "保存",
    delete: "删除",
    undo: "撤销",
    withdraw: "撤回",
    complete: "完成",
    edit: "编辑",
    cancel: "取消",
    close: "关闭",
    retry: "重试",
    open: "打开",
    later: "稍后",
    notNow: "暂不",
    tomorrow: "明天",
    copy: "复制",
    gotIt: "知道了",
  },
  chip: {
    overdue: "已逾期",
    failed: "失败",
    limitReached: "已达上限",
    today: "今天",
    tonight: "今晚",
    daysLeft: "还剩{count}天",
    waitlist: "候补中",
    estimated: "推测",
    draft: "草稿",
    waitingSync: "待同步",
    inReview: "审核中",
    awaitingConfirmation: "待你确认",
    awaitingApproval: "等待对方同意",
    confirmed: "已确认参加",
    completed: "已完成",
    published: "已公开",
    recommended: "推荐",
    upcoming: "未开始",
    going: "计划参加",
    registered: "已报名",
    notRegistered: "未报名",
    followUp: "需跟进",
    declineSuggested: "建议暂缓",
  },
  toast: {
    completed: "已完成",
    movedToTomorrow: "已改到明天",
    addedToTasks: "已添加到待办",
    saveFailed: "无法保存",
    savedOffline: "已离线保存",
    syncLater: "联网后同步",
    copied: "已复制",
    deleted: "已删除",
  },
  confirm: {
    deleteTitle: "要删除{item}吗？",
    delete: "删除",
    irreversible: "此操作无法撤销。",
  },
  filter: {
    clear: "清除",
    showItems: "显示{count}项",
    showPeople: "显示{count}人",
    loosen: "放宽条件",
  },
  aiCard: {
    why: "依据：{reason}",
    showWhy: "查看依据",
    add: "添加",
    decline: "暂不",
    added: "已添加",
    addFailed: "无法添加到{target}",
    nothingWritten: "没有写入任何内容。",
    reconnect: "重新连接",
  },
  offline: {
    banner: "离线 · 修改会在联网后同步",
    pending: "待同步{count}",
    synced: "已同步",
  },
  error: {
    loadFailed: "无法加载{item}",
    checkConnection: "请检查网络后重试。",
    inputKept: "已输入的内容没有丢失。",
    viewCached: "查看本机已保存的内容",
    screenFailed: "无法显示页面",
    screenFailedBody: "数据没有丢失，请重试。",
    needsNetwork: "此页面需要联网",
    needsNetworkBody: "请联网后重试。",
    signInRequired: "请先登录",
    noAccess: "你没有打开此页面的权限",
  },
  degraded: {
    iorbitUnavailable: "iOrbit 暂时无法使用",
    iorbitStopped: "建议和草稿生成已暂停。待办、日程和笔记可以照常使用。",
  },
  loading: {
    loading: "加载中…",
    slow: "加载时间比平时长",
  },
  sample: {
    banner: "正在显示示例 · 数字和人物均为虚构",
    tag: "示例",
  },
  quota: {
    left: "本月还剩{count}次",
    reached: "本月已达上限",
  },
  push: {
    openTarget: "打开",
    remindInHour: "1小时后再提醒",
    markRead: "在收件箱中标为已读",
    fewerLikeThis: "减少此类通知",
    openedFromPush: "从通知打开",
  },
  permission: {
    allowCamera: "允许使用相机",
    allowNotifications: "允许通知",
    notNow: "暂不",
    openSettings: "打开设置",
  },
  homeEdit: {
    edit: "编辑",
    done: "完成",
    comingSoon: "即将上线",
  },
  draftBoundary: {
    create: "生成草稿",
    open: "打开草稿",
    copy: "复制",
    openInMail: "用邮件应用打开",
    notice: "不会替你发送 · 由你自己发送",
    noMessage: "不附加消息 · 之后可以撤回",
  },
} as const;
