"use client";

import { useOrbitLanguage } from "../../orbit-language-context";
import type { ContactsStructureDetailView } from "./contacts-structure-route-service";

export function ContactsStructureDetail({ view }: { view: ContactsStructureDetailView }) {
  const { t, preserveHref } = useOrbitLanguage();
  const strengthLabel = (value: "strong" | "warm" | "weak") => value === "strong" ? t({ zh: "强关系", en: "Strong", ja: "強い関係" }) : value === "warm" ? t({ zh: "中关系", en: "Warm", ja: "中程度の関係" }) : t({ zh: "弱关系", en: "Weak", ja: "弱い関係" });
  return <div className="analysis-content">
    <a className="btn btn-ghost btn-sm" href={preserveHref("/app/contacts/dashboard?tab=structure")}>{t({ zh: "返回人脉结构", en: "Back to network structure", ja: "人脈の構成に戻る" })}</a>
    {view.state === "error" ? <section className="card analysis-card" role="alert" style={{ marginTop: 20 }}><h1 className="h-section">{t({ zh: "暂时无法加载分组", en: "Could not load this group", ja: "グループを読み込めませんでした" })}</h1><p>{t({ zh: "请刷新重试，或返回人脉结构重新选择分组。", en: "Refresh to retry, or go back and select a group again.", ja: "再読み込みするか、戻ってグループを選び直してください。" })}</p><button className="btn btn-ghost" onClick={() => window.location.reload()}>{t({ zh: "重试", en: "Retry", ja: "再試行" })}</button></section> : <>
      <header style={{ margin: "24px 0" }}><div className="eyebrow">{t({ zh: "分组详情", en: "Group details", ja: "グループ詳細" })}</div><h1 className="h-display" style={{ margin: "8px 0" }}>{view.label}</h1><p className="analysis-muted">{view.count} / {view.total} · {view.percentage}%</p>{view.missingData ? <p className="analysis-muted">{t({ zh: "这些联系人尚未填写该信息，可在联系人详情中补充。", en: "These contacts are missing this information. You can add it in their profiles.", ja: "この情報が未入力の連絡先です。連絡先の詳細画面で補完できます。" })}</p> : null}</header>
      <div className="analysis-grid"><section className="card analysis-card"><h2>{t({ zh: "关系质量", en: "Relationship quality", ja: "関係の質" })}</h2>{view.quality.map((item) => <div key={item.id} style={{ marginBottom: 14 }}><div style={{ display: "flex", justifyContent: "space-between" }}><span>{strengthLabel(item.id)}</span><span>{item.count} · {item.percentage}%</span></div><meter aria-label={strengthLabel(item.id)} value={item.percentage} min={0} max={100} style={{ width: "100%" }} /></div>)}</section><section className="card analysis-card"><h2>{t({ zh: "共同标签", en: "Common tags", ja: "共通タグ" })}</h2><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{view.commonTags.map((tag) => <span key={tag.label} className="chip">{tag.label} · {tag.count}</span>)}</div>{view.commonTags.length === 0 ? <p className="analysis-muted">{t({ zh: "暂无共同标签", en: "No common tags", ja: "共通タグはありません" })}</p> : null}<p className="analysis-muted">{view.insight}</p></section></div>
      <section className="card analysis-card" style={{ marginTop: 18 }}><h2>{t({ zh: "这组联系人", en: "Contacts in this group", ja: "このグループの連絡先" })} · {view.count}</h2>{view.contacts.map((contact) => <a key={contact.id} href={preserveHref(contact.href)} className="analysis-notice" style={{ display: "flex", justifyContent: "space-between", gap: 14, color: "inherit", textDecoration: "none" }}><div style={{ minWidth: 0 }}><strong>{contact.name}</strong><p className="analysis-muted" style={{ margin: "4px 0" }}>{[contact.role, contact.organization, contact.location].filter(Boolean).join(" · ")}</p><div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{contact.tags.map((tag) => <span className="chip" key={tag}>{tag}</span>)}</div></div><span className="analysis-muted" style={{ flexShrink: 0 }}>{strengthLabel(contact.strength)}</span></a>)}{view.contacts.length === 0 ? <p className="analysis-muted">{t({ zh: "这组暂无联系人", en: "No contacts in this group", ja: "このグループに連絡先はありません" })}</p> : null}</section>
    </>}
  </div>;
}
