import type { OrbitCopyTable } from "./types";

// R23: the plan v2.2 generation flow on the Web — goal input (Task › プラン empty
// state), the flow page (背景 / 質問 / 前提 / 初版 / AI 修正), manual edit and the
// minimal confirmed card. Question prompts, options, capability and short names come
// from shared/compute/plan-template-copy.ts (planCopy), not from here.
export const planFlowCopy = {
  // ① 目標入力
  goalTitle: { ja: "何を達成したいですか？", zh: "想达成什么目标？", en: "What do you want to achieve?", kind: "label" },
  goalLead: { ja: "うまく言葉にならなくても大丈夫です。iOrbit が、あなたとチームのことを確認しながら具体的にします。", zh: "说不清楚也没关系。iOrbit 会一边确认你和团队的情况，一边把它变具体。", en: "It does not need to be precise. iOrbit checks your situation and your team with you and makes it concrete.", kind: "sentence" },
  goalInputLabel: { ja: "目標", zh: "目标", en: "Goal", kind: "label" },
  goalPlaceholder: { ja: "例：新しいサービスを有料にして黒字化したい", zh: "例：把新服务做成付费并实现盈利", en: "e.g. Turn the new service into a paying business", kind: "label" },
  kindLabel: { ja: "目標タイプ", zh: "目标类型", en: "Goal type", kind: "label" },
  kindHint: { ja: "目標タイプは文から推測 · 変えられます", zh: "目标类型按文字推测 · 可以修改", en: "Guessed from your words · you can change it", kind: "label" },
  start: { ja: "iOrbit と具体化する", zh: "和 iOrbit 一起细化", en: "Shape it with iOrbit", kind: "fullButton" },
  flowLine1: { ja: "背景の確認 → 質問 5つまで → AI の初版", zh: "确认背景 → 最多5个问题 → AI 初稿", en: "Background → up to 5 questions → AI first draft", kind: "label" },
  flowLine2: { ja: "→ AI 修正 3回まで → 手動編集 1回", zh: "→ AI 修改最多3次 → 手动编辑1次", en: "→ up to 3 AI revisions → 1 manual edit", kind: "label" },
  flowTitle: { ja: "このあとの流れ", zh: "接下来的流程", en: "What happens next", kind: "label" },
  flowLimits: { ja: "回数の上限つき", zh: "有次数上限", en: "With set limits", kind: "chip" },
  flowStep1: { ja: "背景の確認", zh: "确认背景", en: "Background", kind: "label" },
  flowStep1Body: { ja: "わたし · チーム · 目的を AI がまとめて下書き → 順に確認", zh: "AI 一次写好 我 · 团队 · 目的 → 依次确认", en: "AI drafts you · team · purpose at once → confirm in order", kind: "label" },
  flowStep2: { ja: "質問 5つまで", zh: "最多5个问题", en: "Up to 5 questions", kind: "label" },
  flowStep2Body: { ja: "背景でわからないことだけ、一度に聞きます", zh: "只问背景里不清楚的，一次问完", en: "Only what the background leaves open, all at once", kind: "label" },
  flowStep3: { ja: "AI の初版", zh: "AI 初稿", en: "AI first draft", kind: "label" },
  flowStep3Body: { ja: "ステップ · 話すべき人のタイプ · 業界の現状", zh: "步骤 · 该聊的人的类型 · 行业现状", en: "Steps · types of people to talk to · industry facts", kind: "label" },
  flowStep4: { ja: "AI 修正 3回まで", zh: "AI 修改最多3次", en: "Up to 3 AI revisions", kind: "label" },
  flowStep4Body: { ja: "変更点だけを表示 · 変更なしも 1回", zh: "只显示改动 · 没改也算1次", en: "Only the changes · no change still counts", kind: "label" },
  flowStep5: { ja: "手動編集 1回", zh: "手动编辑1次", en: "1 manual edit", kind: "label" },
  flowStep5Body: { ja: "名前 · 順番 · 人数と配点（合計 100）", zh: "名称 · 顺序 · 人数和配分（合计100）", en: "Names · order · people and points (total 100)", kind: "label" },
  sampleTitle: { ja: "人物タイプは、こう具体的になります", zh: "人物类型会具体成这样", en: "Person types get this specific", kind: "label" },
  sampleNote: { ja: "肩書きではなく「役割 × 状況」で示します · 話した人のタイプで加点 · 満点 100 · 上限なし", zh: "不看头衔，用「角色 × 处境」来描述 · 按聊过的人的类型加分 · 满分100 · 不封顶", en: "Role × situation, not job titles · points by the type of person you talk to · 100 is full · no cap", kind: "label" },
  sampleCandidates: { ja: "人脈の候補", zh: "人脉中的候选", en: "In your network", kind: "label" },
  sampleEvents: { ja: "会える活動", zh: "能见到的活动", en: "Events to meet", kind: "label" },
  sampleRoutes: { ja: "紹介ルート", zh: "引荐路径", en: "Intro routes", kind: "label" },
  sampleVc: { ja: "シリーズA のリードを取ったことがある、SaaS に強い VC のパートナー", zh: "领投过 A 轮、熟悉 SaaS 的 VC 合伙人", en: "A VC partner strong in SaaS who has led Series A rounds", kind: "label" },
  sampleAngel: { ja: "自分で事業を売却し、いまは同じ分野の創業者に出資しているエンジェル", zh: "自己卖过公司、现在投资同领域创始人的天使", en: "An angel who sold a company and now backs founders in the same field", kind: "label" },
  sampleCvc: { ja: "事業会社の新規事業部で、出資と提携をあわせて検討している CVC 担当者", zh: "在企业新业务部门、同时考虑投资与合作的企业投资人", en: "A corporate VC lead weighing investment and partnership together", kind: "label" },
  resumeLabel: { ja: "作りかけのプラン：{goal}", zh: "未完成的计划：{goal}", en: "Plan in progress: {goal}", kind: "label" },
  resume: { ja: "続ける", zh: "继续", en: "Continue", kind: "button" },
  limitGoalsMonth: { ja: "今月はこれ以上新しい目標を作れません。", zh: "本月不能再新建目标了。", en: "No more new goals can be created this month.", kind: "sentence" },
  limitActiveGoals: { ja: "同時に進められる目標は 2 つまでです。", zh: "同时进行的目标最多2个。", en: "Up to 2 goals can be in progress at once.", kind: "sentence" },
  // 已確定 最小卡
  confirmedTitle: { ja: "プランを確定しました。", zh: "计划已确定。", en: "Your plan is confirmed.", kind: "sentence" },
  confirmedScore: { ja: "スコア", zh: "得分", en: "Score", kind: "label" },
  confirmedScoreNote: { ja: "満点 100 · 上限なし", zh: "满分100 · 不封顶", en: "100 is full · no cap", kind: "label" },
  // ② 生成流程
  flowPageTitle: { ja: "プランを作る", zh: "制定计划", en: "Make a plan", kind: "label" },
  stageBackground: { ja: "背景の確認", zh: "确认背景", en: "Background", kind: "label" },
  stageQuestions: { ja: "質問", zh: "问题", en: "Questions", kind: "label" },
  stageDraft: { ja: "初版", zh: "初稿", en: "First draft", kind: "label" },
  stageFix: { ja: "AI 修正", zh: "AI 修改", en: "AI revisions", kind: "label" },
  stageManual: { ja: "手動編集", zh: "手动编辑", en: "Manual edit", kind: "label" },
  progressShortBackground: { ja: "背景", zh: "了解背景", en: "Background", kind: "label" },
  progressLabel: { ja: "進み具合", zh: "进度", en: "Progress", kind: "label" },
  goalLine: { ja: "目標：{goal}", zh: "目标：{goal}", en: "Goal: {goal}", kind: "label" },
  backgroundLead: { ja: "プロフィール・目標・人脈から、あなた · チーム · 目的の 3つをまとめて下書きしました。上から順に、違うところだけ直してください。", zh: "根据资料、目标和人脉，一次写好了 你 · 团队 · 目的 三部分。请从上往下，只改不对的地方。", en: "From your profile, goal and network, iOrbit drafted you · team · purpose together. Go top to bottom and fix only what is off.", kind: "sentence" },
  readingTitle: { ja: "読んでいるもの", zh: "正在读取", en: "Reading", kind: "label" },
  readingProfile: { ja: "プロフィール", zh: "个人资料", en: "Profile", kind: "chip" },
  readingGoal: { ja: "目標文", zh: "目标描述", en: "Goal text", kind: "chip" },
  readingNetwork: { ja: "人脈", zh: "人脉", en: "Network", kind: "chip" },
  readingCapabilities: { ja: "必要な力", zh: "所需能力", en: "Needed skills", kind: "chip" },
  draftingBackground: { ja: "背景を下書きしています…", zh: "正在起草背景…", en: "Drafting the background…", kind: "label" },
  backgroundFailed: { ja: "下書きできませんでした · 自分で選べます", zh: "没能起草 · 可以自己选择", en: "Could not draft this · you can choose yourself", kind: "label" },
  retryOnce: { ja: "もう一度", zh: "再试一次", en: "Try again", kind: "button" },
  blockMe: { ja: "わたし", zh: "我", en: "You", kind: "label" },
  blockTeam: { ja: "チーム", zh: "团队", en: "Team", kind: "label" },
  blockPurpose: { ja: "目的", zh: "最终目的", en: "Purpose", kind: "label" },
  checking: { ja: "確認中", zh: "确认中", en: "Checking", kind: "chip" },
  draftSummary: { ja: "下書き：{text}", zh: "草稿：{text}", en: "Draft: {text}", kind: "label" },
  editBlock: { ja: "{block}を直す", zh: "修改{block}", en: "Edit {block}", kind: "label" },
  fromProfile: { ja: "プロフィールから", zh: "来自资料", en: "From profile", kind: "chip" },
  fromGoal: { ja: "目標文から", zh: "来自目标", en: "From the goal", kind: "chip" },
  stanceLabel: { ja: "立場", zh: "立场", en: "Your role", kind: "label" },
  stanceOwner: { ja: "代表・オーナー", zh: "负责人", en: "Owner", kind: "chip" },
  stanceCofounder: { ja: "共同創業者", zh: "联合创始人", en: "Co-founder", kind: "chip" },
  stanceEmployee: { ja: "社内の担当者", zh: "公司内负责人", en: "In-house lead", kind: "chip" },
  stanceIndividual: { ja: "個人として", zh: "以个人身份", en: "As an individual", kind: "chip" },
  wantsLabel: { ja: "やりたいこと", zh: "想做的事", en: "What you want to do", kind: "label" },
  confirmMe: { ja: "わたしを確定 → チームへ", zh: "确认我 → 团队", en: "Confirm, then team", kind: "fullButton" },
  teamMode: { ja: "体制", zh: "形式", en: "Setup", kind: "label" },
  teamSolo: { ja: "一人", zh: "一个人", en: "Solo", kind: "chip" },
  teamTeam: { ja: "チーム", zh: "团队", en: "Team", kind: "chip" },
  capabilitiesHead: { ja: "必要な力 {count} · 固定", zh: "所需能力{count}项 · 固定", en: "{count} needed skills · fixed", kind: "label" },
  capabilitiesWhy: { ja: "{count} 項目は目標タイプごとに固定で、AI が考えたものではありません", zh: "这{count}项按目标类型固定，不是 AI 现想的", en: "These items are fixed per goal type ({count}), not made up by AI", kind: "label" },
  sourceProfile: { ja: "プロフィール", zh: "资料", en: "Profile", kind: "chip" },
  sourceNetwork: { ja: "人脈から", zh: "来自人脉", en: "Network", kind: "chip" },
  sourceManual: { ja: "手入力", zh: "手动输入", en: "Typed in", kind: "chip" },
  basisNetwork: { ja: "名刺・面談メモから", zh: "根据名片与面谈记录", en: "From cards and notes", kind: "label" },
  gap: { ja: "空き", zh: "空缺", en: "Gap", kind: "chip" },
  covered: { ja: "{count}人", zh: "{count}位", en: "{count} ppl", kind: "chip" },
  teamHint: { ja: "チェックはクリックで付け外し · 空きはその場で計算 · 「＋ 追加」で人脈から / 自分で書く", zh: "点击勾选或取消 · 空缺即时计算 ·「＋ 添加」可从人脉选或自己写", en: "Click to tick or untick · gaps update at once · \"+ Add\" picks from your network or lets you write one in", kind: "label" },
  addMember: { ja: "メンバーを追加", zh: "添加成员", en: "Add member", kind: "button" },
  toggleCapability: { ja: "{name} · {capability}", zh: "{name} · {capability}", en: "{name} · {capability}", kind: "label" },
  confirmTeam: { ja: "チームを確定 → 目的へ", zh: "确认团队 → 目的", en: "Confirm, then purpose", kind: "fullButton" },
  purposeQuestion: { ja: "最終的な目的は、どれがいちばん近い？", zh: "最终目的最接近哪一个？", en: "Which is closest to what you are really after?", kind: "label" },
  purposeHint: { ja: "上ほど大きい目的です。小さすぎ・大きすぎと感じたら 1段ずらしてください。", zh: "越往上目的越大。觉得太小或太大，就挪一级。", en: "Higher means bigger. If it feels too small or too big, move one step.", kind: "sentence" },
  rungBig: { ja: "大きめ · 10年単位", zh: "较大 · 以十年计", en: "Bigger · over 10 years", kind: "label" },
  rungSmall: { ja: "小さめ · 数か月", zh: "较小 · 几个月", en: "Smaller · a few months", kind: "label" },
  rungOriginal: { ja: "最初に書いた目標", zh: "最初写的目标", en: "What you wrote", kind: "label" },
  rungSuggested: { ja: "いちばん近い？", zh: "最接近？", en: "Closest?", kind: "label" },
  purposeWhy: { ja: "階段は目標文と「やりたいこと」「チーム」から決まり、AI は近い段を 1つ提案するだけです", zh: "阶梯由目标、「想做的事」和「团队」决定，AI 只建议最接近的一级", en: "The steps come from your goal, what you want to do and your team; AI only suggests the closest one", kind: "label" },
  confirmPurpose: { ja: "目的を確定", zh: "确认目的", en: "Confirm purpose", kind: "fullButton" },
  toQuestions: { ja: "この背景で質問へ（5問まで）", zh: "按这个背景提问（最多5题）", en: "On to questions (max 5)", kind: "fullButton" },
  backgroundDone: { ja: "背景を確認しました · 目的：{purpose}", zh: "背景已确认 · 目的：{purpose}", en: "Background confirmed · purpose: {purpose}", kind: "label" },
  // メンバーを追加
  addMemberTitle: { ja: "メンバーを追加", zh: "添加成员", en: "Add a member", kind: "dialogTitle" },
  addMemberTabs: { ja: "追加のしかた", zh: "添加方式", en: "How to add", kind: "label" },
  tabNetwork: { ja: "人脈から選ぶ", zh: "从人脉选", en: "From network", kind: "tab" },
  tabManual: { ja: "自分で書く", zh: "自己写", en: "Write in", kind: "tab" },
  searchPlaceholder: { ja: "名前・会社・タグで検索", zh: "按姓名、公司、标签搜索", en: "Search by name, company or tag", kind: "label" },
  searchEmpty: { ja: "名前を入れると、人脈から探します", zh: "输入名字后，会在人脉里查找", en: "Type a name to search your network", kind: "label" },
  searchNone: { ja: "見つかりませんでした", zh: "没有找到", en: "No matches", kind: "label" },
  cofounderChip: { ja: "共同創業者", zh: "联合创始人", en: "Co-founder", kind: "chip" },
  gapChip: { ja: "空き：{label}", zh: "空缺：{label}", en: "Gap: {label}", kind: "chip" },
  addSelected: { ja: "{count}名を追加", zh: "添加{count}人", en: "Add {count}", kind: "fullButton" },
  nameLabel: { ja: "名前か呼び名", zh: "姓名或称呼", en: "Name or nickname", kind: "label" },
  relationLabel: { ja: "関わり方", zh: "参与方式", en: "How they take part", kind: "label" },
  relationCofounder: { ja: "共同創業者", zh: "联合创始人", en: "Co-founder", kind: "chip" },
  relationEmployee: { ja: "社員", zh: "员工", en: "Employee", kind: "chip" },
  relationContractor: { ja: "業務委託", zh: "外包合作", en: "Contractor", kind: "chip" },
  relationAdvisor: { ja: "アドバイザー", zh: "顾问", en: "Advisor", kind: "chip" },
  canDoLabel: { ja: "できること", zh: "能做的事", en: "What they can do", kind: "label" },
  otherCapability: { ja: "＋ その他", zh: "＋ 其他", en: "+ Other", kind: "chip" },
  otherPlaceholder: { ja: "その他にできること（「、」で区切る）", zh: "其他能做的事（用「、」分隔）", en: "Other skills (separate with commas)", kind: "label" },
  alsoNetwork: { ja: "人脈にも登録する", zh: "也加入人脉", en: "Also add to my network", kind: "label" },
  alsoNetworkHint: { ja: "オフならこのプランの中だけ", zh: "关闭时只在这个计划里", en: "When off, they stay inside this plan", kind: "label" },
  addManual: { ja: "追加する", zh: "添加", en: "Add", kind: "button" },
  // ≤5 問
  questionsLead: { ja: "背景の空白から、プランを分ける質問だけ聞かせてください。まとめて答えられます。", zh: "根据背景里的空白，只问会影响计划走向的问题。可以一次答完。", en: "Only the questions that change the plan, picked from the gaps in your background. Answer them all at once.", kind: "sentence" },
  questionsTitle: { ja: "あと {count} つだけ、確認させてください", zh: "只再确认{count}个问题", en: "Just {count} more to check", kind: "label" },
  questionBank: { ja: "題庫「{kind}」", zh: "题库「{kind}」", en: "Question set: {kind}", kind: "label" },
  questionsWhy: { ja: "選んだ理由", zh: "选题理由", en: "Why these", kind: "label" },
  guessTag: { ja: "推測", zh: "推测", en: "Guess", kind: "chip" },
  freeText: { ja: "自由に書く（任意）", zh: "自由填写（可选）", en: "Add a note (optional)", kind: "label" },
  answerAll: { ja: "まとめて回答する（{count}問）", zh: "一次回答（{count}题）", en: "Answer all ({count})", kind: "fullButton" },
  answerNote: { ja: "空欄は推測で進め、依拠に「推測」と書きます", zh: "空着的题按推测处理，依据里会写「推测」", en: "Blank answers are guessed and marked \"guess\" in the basis", kind: "label" },
  // 確定した前提
  premiseTitle: { ja: "確定した前提", zh: "确定的前提", en: "Agreed premises", kind: "label" },
  premiseHint: { ja: "行をクリックで直せます", zh: "点击某一行即可修改", en: "Click a row to change it", kind: "label" },
  premiseSourceBackground: { ja: "背景", zh: "背景信息", en: "Background", kind: "chip" },
  premiseRedo: { ja: "前提を直すと初版をつくり直します。回数には含みません。", zh: "改前提会重做初稿，不计入次数。", en: "Changing a premise remakes the first draft. It does not count as a revision.", kind: "sentence" },
  premiseChoice: { ja: "選択肢", zh: "选项", en: "Option", kind: "label" },
  premiseValue: { ja: "内容", zh: "内容说明", en: "Text", kind: "label" },
  makeDraft: { ja: "この前提で初版をつくる", zh: "按这些前提做初稿", en: "Make the first draft", kind: "fullButton" },
  makeDraftNote: { ja: "初版は回数に含みません · この後 AI 修正 3回 + 手動編集 1回", zh: "初稿不计次数 · 之后可 AI 修改3次 + 手动编辑1次", en: "The first draft is free · then 3 AI revisions + 1 manual edit", kind: "label" },
  makingDraft: { ja: "初版をつくっています · 数十秒かかることがあります", zh: "正在做初稿 · 可能需要几十秒", en: "Making the first draft · this can take a minute", kind: "label" },
  showAll: { ja: "すべて見る", zh: "查看全部", en: "Show all", kind: "button" },
  // 初版 / 方案
  draftLead: { ja: "前提と、業界の現状をもとに初版をつくりました。", zh: "根据前提和行业现状做了初稿。", en: "iOrbit made a first draft from the premises and industry facts.", kind: "sentence" },
  draftTitle: { ja: "AI の初版 · 方案", zh: "AI 初稿 · 方案", en: "AI first draft · plan", kind: "label" },
  diagnosis: { ja: "見立て", zh: "判断", en: "Diagnosis", kind: "label" },
  conclusion: { ja: "進め方の結論", zh: "推进结论", en: "How to proceed", kind: "label" },
  stepsTitle: { ja: "ステップ · 完了の目安", zh: "步骤 · 完成标准", en: "Steps · done when", kind: "label" },
  doneCriteria: { ja: "目安：{text}", zh: "标准：{text}", en: "Done when: {text}", kind: "label" },
  typesTitle: { ja: "話すべき人のタイプ · 配点", zh: "该聊的人的类型 · 配分", en: "People to talk to · points", kind: "label" },
  typePoints: { ja: "{points} 点 · {count}人", zh: "{points}分 · {count}人", en: "{points} pts · {count} ppl", kind: "label" },
  eventPoints: { ja: "{points} 点 · {count}回", zh: "{points}分 · {count}次", en: "{points} pts · {count}×", kind: "label" },
  allocationWhy: { ja: "配点の理由", zh: "配分理由", en: "Why these points", kind: "label" },
  citationsTitle: { ja: "この案で参考にした業界の現状 {count}件", zh: "本方案参考的行业现状{count}条", en: "Industry facts used ({count})", kind: "label" },
  citationVersion: { ja: "v{version} · {date}", zh: "第{version}版 · {date}", en: "v{version} · {date}", kind: "label" },
  citationSource: { ja: "出典：{label}", zh: "出处：{label}", en: "Source: {label}", kind: "label" },
  citationsNote: { ja: "AI は Orbit が管理するこのライブラリの資料だけを引用します。", zh: "AI 只引用 Orbit 维护的这个资料库。", en: "AI only cites this library, which Orbit maintains.", kind: "sentence" },
  // AI 修正
  fixLeftBefore: { ja: "AI 修正 あと", zh: "AI 修改还剩", en: "AI revisions left", kind: "label" },
  fixLeftAfter: { ja: "回 / {limit}回", zh: "次 / 共{limit}次", en: "of {limit}", kind: "label" },
  fixFreeNote: { ja: "初版は回数に含みません", zh: "初稿不计次数", en: "The first draft is free", kind: "label" },
  fixTip: { ja: "現状と考えを、できるだけ一度にまとめて書いてください。", zh: "请把现状和想法尽量一次写完。", en: "Write your situation and thinking in one go if you can.", kind: "sentence" },
  fixExample: { ja: "例：「営業は当面 2人でやる。仲間はデザインを優先する。最初の 1回は無料で試してほしい。」", zh: "例：「销售暂时两个人做。伙伴优先找设计。希望第一次免费试用。」", en: "e.g. \"The two of us handle sales for now. Find a designer first. Let the first try be free.\"", kind: "label" },
  fixPlaceholder: { ja: "修正したいことを入力", zh: "输入想修改的内容", en: "What should change?", kind: "label" },
  fixSend: { ja: "修正する", zh: "修改", en: "Revise", kind: "button" },
  fixUsedUp: { ja: "修正は使い切りました。手動で編集するか、この内容で確定します。", zh: "修改次数已用完。可以手动编辑，或按现在的内容确定。", en: "All revisions are used. Edit by hand or confirm as it is.", kind: "sentence" },
  fixCountsNote: { ja: "変更がなかった回も 1回と数えます。", zh: "没有改动的那次也算1次。", en: "A round with no change still counts as one.", kind: "sentence" },
  manualEdit: { ja: "手動で編集", zh: "手动编辑", en: "Edit by hand", kind: "button" },
  confirmPlan: { ja: "この内容で確定", zh: "按此内容确定", en: "Confirm this plan", kind: "fullButton" },
  turnTitle: { ja: "AI 修正 {n} / {limit} を反映 · 方案を更新しました", zh: "已应用第{n}/{limit}次 AI 修改 · 方案已更新", en: "AI revision {n} / {limit} applied · plan updated", kind: "label" },
  changedTag: { ja: "変更", zh: "变更", en: "Changed", kind: "chip" },
  unchanged: { ja: "変わらない点：{list}", zh: "不变的部分：{list}", en: "Unchanged: {list}", kind: "label" },
  noChange: { ja: "今回は変更しません", zh: "这次不做修改", en: "No change this time", kind: "label" },
  historyLabel: { ja: "修正の履歴", zh: "修改记录", en: "Revision history", kind: "label" },
  turnChip: { ja: "{n}：{text}", zh: "{n}：{text}", en: "{n}: {text}", kind: "label" },
  listSeparator: { ja: "・", zh: "、", en: ", ", kind: "label" },
  yourMessage: { ja: "あなた", zh: "你", en: "You", kind: "label" },
  // 错误与上限
  draftFailed: { ja: "初版をつくれませんでした", zh: "没能做出初稿", en: "Could not make the first draft", kind: "label" },
  draftFailedBody: { ja: "何も保存していません。", zh: "什么都没有保存。", en: "Nothing was saved.", kind: "sentence" },
  fixFailed: { ja: "修正できませんでした", zh: "没能修改", en: "Could not revise the plan", kind: "label" },
  fixFailedBody: { ja: "回数は減っていません。", zh: "次数没有减少。", en: "No revision was used.", kind: "sentence" },
  stepFailed: { ja: "この操作を完了できませんでした", zh: "这个操作没能完成", en: "Could not finish this step", kind: "label" },
  limitDaily: { ja: "今日はここまでです · 明日また使えます。", zh: "今天就到这里 · 明天可以再用。", en: "That is all for today · available again tomorrow.", kind: "sentence" },
  limitMonthly: { ja: "今月の上限に達しました（来月 1日から）", zh: "已达本月上限（下月1日起恢复）", en: "Monthly limit reached (back on the 1st)", kind: "label" },
  stale: { ja: "別の端末で変更されました", zh: "已在其他设备上修改", en: "Changed on another device", kind: "label" },
  reload: { ja: "読み直す", zh: "重新读取", en: "Reload", kind: "button" },
  loadFailed: { ja: "プランを読み込めませんでした", zh: "没能读取计划", en: "Could not load the plan", kind: "label" },
  // 右栏
  railKnown: { ja: "わかったこと", zh: "已了解的情况", en: "What iOrbit knows", kind: "label" },
  railMe: { ja: "わたし", zh: "我", en: "You", kind: "label" },
  railWants: { ja: "やりたいこと", zh: "想做的事", en: "Wants to", kind: "label" },
  railSetup: { ja: "体制", zh: "形式", en: "Setup", kind: "label" },
  railGaps: { ja: "空白", zh: "缺口", en: "Gaps", kind: "label" },
  railPurpose: { ja: "目的", zh: "最终目的", en: "Purpose", kind: "label" },
  railPremise: { ja: "前提", zh: "前提条件", en: "Premises", kind: "label" },
  railSolo: { ja: "一人", zh: "一个人", en: "Solo", kind: "label" },
  railTeam: { ja: "チーム {count}名（{names}）", zh: "团队{count}人（{names}）", en: "Team of {count} ({names})", kind: "label" },
  railNoGap: { ja: "なし", zh: "无", en: "None", kind: "label" },
  railPremisePending: { ja: "質問のあとに、ここへまとまります", zh: "回答问题后会汇总在这里", en: "Collected here after the questions", kind: "label" },
  railNext: { ja: "このあと", zh: "接下来", en: "Next", kind: "label" },
  railNext1: { ja: "② 質問", zh: "② 问题", en: "② Questions", kind: "label" },
  railNext1Body: { ja: "5つまで · まとめて回答", zh: "最多5个 · 一次回答", en: "Up to 5 · answer at once", kind: "label" },
  railNext2: { ja: "③ 初版", zh: "③ 初稿", en: "③ First draft", kind: "label" },
  railNext2Body: { ja: "方案 + 業界の現状", zh: "方案 + 行业现状", en: "Plan + industry facts", kind: "label" },
  railNext3: { ja: "④ AI 修正", zh: "④ AI 修改", en: "④ AI revisions", kind: "label" },
  railNext3Body: { ja: "3回まで", zh: "最多3次", en: "Up to 3", kind: "label" },
  railNext4: { ja: "⑤ 手動編集", zh: "⑤ 手动编辑", en: "⑤ Manual edit", kind: "label" },
  railNext4Body: { ja: "1回 · 合計 100 を保つ", zh: "1次 · 合计保持100", en: "Once · total stays 100", kind: "label" },
  railDraft: { ja: "方案の下書き", zh: "方案草稿", en: "Plan draft", kind: "label" },
  railChanged: { ja: "今回の変更", zh: "本次改动", en: "Just changed", kind: "chip" },
  // ③ 手動編集
  editTitle: { ja: "プランを手動で編集", zh: "手动编辑计划", en: "Edit the plan by hand", kind: "label" },
  editSub: { ja: "1回だけ · 保存すると確定", zh: "只有1次 · 保存即确定", en: "Once only · saving confirms it", kind: "label" },
  editSteps: { ja: "ステップ", zh: "步骤", en: "Steps", kind: "label" },
  editStepsHint: { ja: "ドラッグで並べ替え · 名前と目安はクリックで編集", zh: "拖动排序 · 点击名称和标准即可编辑", en: "Drag to reorder · click a name or target to edit", kind: "label" },
  origin: { ja: "元：{title}", zh: "原：{title}", en: "Was: {title}", kind: "label" },
  addStep: { ja: "Step を追加", zh: "添加步骤", en: "Add a step", kind: "button" },
  stepTitleLabel: { ja: "Step の名前", zh: "步骤名称", en: "Step name", kind: "label" },
  stepDoneLabel: { ja: "完了の目安", zh: "完成标准", en: "Done when", kind: "label" },
  stepTypesLabel: { ja: "このステップで話すタイプ", zh: "这一步要聊的类型", en: "Types for this step", kind: "label" },
  moveUp: { ja: "上へ", zh: "上移", en: "Move up", kind: "button" },
  moveDown: { ja: "下へ", zh: "下移", en: "Move down", kind: "button" },
  removeStep: { ja: "この Step を削除", zh: "删除这一步", en: "Remove this step", kind: "label" },
  dragStep: { ja: "{title}を並べ替え", zh: "拖动排序：{title}", en: "Reorder {title}", kind: "label" },
  editTypes: { ja: "人物タイプと配点", zh: "人物类型与配分", en: "Person types and points", kind: "label" },
  editTypesHint: { ja: "5点刻み · 1つ変えると配点の高いタイプから 5点ずつ調整 · 合計 100", zh: "以5分为单位 · 改一项后从配分高的类型起每次调5分 · 合计100", en: "Steps of 5 · change one and the highest types give or take 5 at a time · total 100", kind: "label" },
  colType: { ja: "タイプ", zh: "类型", en: "Type", kind: "label" },
  colTarget: { ja: "目標", zh: "目标人数", en: "Target", kind: "label" },
  colPoints: { ja: "配点", zh: "配分", en: "Points", kind: "label" },
  colCompare: { ja: "AI の方案 → 今", zh: "AI 方案 → 现在", en: "AI plan → now", kind: "label" },
  peopleCount: { ja: "{count}人", zh: "{count}位", en: "{count} ppl", kind: "label" },
  timesCount: { ja: "{count}回", zh: "{count}次", en: "{count}×", kind: "label" },
  decrease: { ja: "{type}を減らす", zh: "减少{type}", en: "Fewer {type}", kind: "label" },
  increase: { ja: "{type}を増やす", zh: "增加{type}", en: "More {type}", kind: "label" },
  pointsOf: { ja: "{type}の配点", zh: "{type}的配分", en: "Points for {type}", kind: "label" },
  notMultiple: { ja: "5点刻みで入力してください", zh: "请按5分为单位输入", en: "Use steps of 5", kind: "label" },
  noRoom: { ja: "ほかのタイプから動かせる点がありません", zh: "其他类型已没有可调的分数", en: "No points left to move from other types", kind: "label" },
  removeType: { ja: "{type}を外す", zh: "移除{type}", en: "Remove {type}", kind: "label" },
  removeTitle: { ja: "{type}を外しますか？", zh: "要移除{type}吗？", en: "Remove {type}?", kind: "confirmTitle" },
  removeBody: { ja: "{points}点を 5点ずつ、配点の高いタイプから順に配り直します。", zh: "这{points}分会按每次5分，从配分高的类型起依次分回去。", en: "Its {points} points go back 5 at a time, highest types first.", kind: "sentence" },
  removeConfirm: { ja: "外す", zh: "移除", en: "Remove", kind: "button" },
  total: { ja: "合計", zh: "合计", en: "Total", kind: "label" },
  addType: { ja: "タイプを追加（テンプレートの枠から選ぶ）", zh: "添加类型（从模板中选）", en: "Add a type", kind: "fullButton" },
  addTypeTitle: { ja: "追加するタイプを選ぶ", zh: "选择要添加的类型", en: "Choose a type to add", kind: "dialogTitle" },
  noMoreTypes: { ja: "テンプレートの枠はすべて使っています", zh: "模板里的类型都已用上", en: "Every template slot is in use", kind: "label" },
  changesTitle: { ja: "変更点", zh: "改动", en: "Changes", kind: "label" },
  changeKindName: { ja: "名前", zh: "名称", en: "Name", kind: "chip" },
  changeKindDone: { ja: "目安", zh: "标准", en: "Target", kind: "chip" },
  changeKindOrder: { ja: "順番", zh: "顺序", en: "Order", kind: "chip" },
  changeKindPoints: { ja: "配点", zh: "配分", en: "Points", kind: "chip" },
  changeKindCount: { ja: "人数", zh: "人数调整", en: "People", kind: "chip" },
  changeKindAdd: { ja: "追加", zh: "新增", en: "Added", kind: "chip" },
  changeKindRemove: { ja: "削除", zh: "删去", en: "Removed", kind: "chip" },
  changeName: { ja: "Step {n}「{from}」→「{to}」", zh: "Step {n}「{from}」→「{to}」", en: "Step {n} \"{from}\" → \"{to}\"", kind: "label" },
  changeDone: { ja: "Step {n} の目安を変更", zh: "第{n}步的完成标准已改", en: "Step {n} target changed", kind: "label" },
  changeOrder: { ja: "「{title}」を {from} → {to}番目", zh: "「{title}」从第{from}步 → 第{to}步", en: "\"{title}\" moved {from} → {to}", kind: "label" },
  changePoints: { ja: "{type} {from} → {to}", zh: "{type} {from} → {to}", en: "{type} {from} → {to}", kind: "label" },
  changeCount: { ja: "{type} {from}人 → {to}人（{units}）", zh: "{type}：{from}人 → {to}人（{units}）", en: "{type} {from} → {to} people ({units})", kind: "label" },
  unitsEven: { ja: "1人 {points}点", zh: "每人{points}分", en: "{points} pts each", kind: "label" },
  unitsUneven: { ja: "{points}点 + 最後の1人 {last}点", zh: "{points}分 + 最后1人{last}分", en: "{points} pts, last one {last}", kind: "label" },
  changeAddStep: { ja: "「{title}」を追加", zh: "添加「{title}」", en: "Added \"{title}\"", kind: "label" },
  changeRemoveStep: { ja: "「{title}」を削除", zh: "删除「{title}」", en: "Removed \"{title}\"", kind: "label" },
  changeAddType: { ja: "{type}を追加", zh: "添加{type}", en: "Added {type}", kind: "label" },
  changeRemoveType: { ja: "{type}を外す", zh: "移除{type}", en: "Removed {type}", kind: "label" },
  noChanges: { ja: "まだ変更はありません", zh: "还没有改动", en: "No changes yet", kind: "label" },
  totalBar: { ja: "合計 {total} / 100 · 変更 {count}件 · 手動編集は 1回だけ", zh: "合计{total}/100 · 改动{count}处 · 手动编辑只有1次", en: "Total {total} / 100 · {count} changed · one manual edit only", kind: "label" },
  startPlan: { ja: "このプランで始める", zh: "按这个计划开始", en: "Start with this plan", kind: "fullButton" },
  savedNote: { ja: "保存したあとは、AI がこのプランを自動で書き換えることはありません。見直したいときは、プラン画面の「方案を見直す」から変更案をつくります。", zh: "保存后，AI 不会再自动改写这个计划。想调整时，从计划页的「重新审视方案」生成修改建议。", en: "After saving, AI never rewrites this plan on its own. To change it later, make a proposal from \"Review the plan\" on the plan screen.", kind: "sentence" },
  manualUsed: { ja: "手動編集はもう使いました", zh: "手动编辑已经用过了", en: "The manual edit is already used", kind: "label" },
  backToFlow: { ja: "方案に戻る", zh: "返回方案", en: "Back to plan", kind: "button" },
  // 確定後（流程页）
  plannedOpen: { ja: "プランを見る", zh: "查看计划", en: "Open the plan", kind: "button" },
} as const satisfies OrbitCopyTable;
