// R03 标准用词源（日语）。纯常量、零 import：经 `npm run sync:contract` 原样复制到
// repos/orbit-app/src/api/copy/。术语和写法见
// docs/designs/redesign-2026-10/sprints/R03-copy-and-ja/{glossary,style-guide}.md；
// 改这里后在 repos/orbits 跑 `npm run copy:qa`，再到 App 跑 `npm run sync:contract`。键名与占位符三语一致（测试守着）。
// 设计稿原样搬运的句子注明出处 `01-system.html:<行>`。

export const ja = {
  nav: {
    home: "ホーム",
    network: "人脈",
    iorbit: "iOrbit",
    events: "イベント",
    task: "Task",
    inbox: "受信箱",
    host: "主催",
    settings: "設定",
    me: "マイページ",
    main: "メインナビゲーション",
    back: "戻る",
    backTo: "{label}に戻る",
    askIorbit: "iOrbit に聞く…",
  },
  taskSegments: {
    calendar: "カレンダー",
    todo: "To-do",
    plan: "プラン",
    notes: "メモ",
  },
  action: {
    add: "追加",
    save: "保存",
    delete: "削除",
    undo: "元に戻す",
    withdraw: "取り消す",
    complete: "完了にする",
    edit: "編集",
    cancel: "キャンセル",
    close: "閉じる",
    retry: "再試行",
    open: "開く",
    later: "あとで",
    notNow: "やめる",
    tomorrow: "明日",
    copy: "コピー",
    gotIt: "わかりました",
  },
  chip: {
    overdue: "期限超過",
    failed: "失敗",
    limitReached: "上限に達しました",
    today: "今日",
    tonight: "今夜",
    daysLeft: "あと{count}日",
    waitlist: "キャンセル待ち",
    estimated: "推定",
    draft: "下書き",
    waitingSync: "同期待ち",
    inReview: "審査中",
    awaitingConfirmation: "確認待ち",
    awaitingApproval: "承認待ち",
    confirmed: "参加確定",
    completed: "完了",
    published: "公開済み",
    recommended: "おすすめ",
    upcoming: "開催前",
    going: "参加予定",
    registered: "申込済み",
    notRegistered: "未申込",
    followUp: "要フォロー",
    declineSuggested: "見送り推奨",
  },
  toast: {
    completed: "完了にしました",
    movedToTomorrow: "明日に移動しました",
    addedToTasks: "タスクに追加しました",
    saveFailed: "保存できませんでした",
    savedOffline: "オフラインで保存しました",
    syncLater: "接続後に同期します",
    copied: "コピーしました",
    deleted: "削除しました",
  },
  confirm: {
    deleteTitle: "この{item}を削除しますか？",
    delete: "削除する",
    irreversible: "元に戻せません。",
  },
  filter: {
    clear: "クリア",
    showItems: "{count}件を表示",
    showPeople: "{count}人を表示",
    loosen: "条件をゆるめる",
  },
  aiCard: {
    why: "根拠：{reason}",
    showWhy: "根拠を見る",
    add: "追加する",
    decline: "やめる",
    added: "追加しました",
    addFailed: "{target}に追加できませんでした",
    nothingWritten: "何も書き込まれていません。",
    reconnect: "再接続",
  },
  offline: {
    banner: "オフライン · 変更は接続後に同期されます",
    pending: "同期待ち {count}",
    synced: "同期しました",
  },
  error: {
    loadFailed: "{item}を読み込めませんでした",
    checkConnection: "通信状況を確認して、もう一度お試しください。",
    inputKept: "入力中の内容は失われていません。",
    viewCached: "端末に保存済みを見る",
    screenFailed: "この画面を表示できませんでした",
    screenFailedBody: "データは失われていません。もう一度お試しください。",
    needsNetwork: "この画面はインターネット接続が必要です",
    needsNetworkBody: "接続してから、もう一度お試しください。",
    signInRequired: "ログインしてください",
    noAccess: "この画面を開く権限がありません",
  },
  degraded: {
    iorbitUnavailable: "iOrbit が一時的に使えません",
    iorbitStopped: "提案と下書きの作成は止まっています。タスク・予定・メモは通常どおり使えます。",
  },
  loading: {
    loading: "読み込み中…",
    slow: "読み込みに時間がかかっています",
  },
  sample: {
    banner: "サンプルを表示中 · 数字や人物は架空です",
    tag: "サンプル",
  },
  quota: {
    left: "今月あと {count} 回",
    reached: "今月の上限に達しました",
  },
  push: {
    openTarget: "開く",
    remindInHour: "1時間後に再通知",
    markRead: "受信箱で既読にする",
    fewerLikeThis: "この種類の通知を減らす",
    openedFromPush: "通知から開きました",
  },
  permission: {
    allowCamera: "カメラを許可する",
    allowNotifications: "通知を許可する",
    notNow: "今はしない",
    openSettings: "設定を開く",
  },
  homeEdit: {
    edit: "編集",
    done: "完了",
    comingSoon: "近日公開",
  },
  draftBoundary: {
    create: "下書きを作成",
    open: "下書きを開く",
    copy: "コピー",
    openInMail: "メールアプリで開く",
    notice: "送信はしません · 送信はあなたが行います",
    noMessage: "メッセージは添えません · あとから取り消せます",
  },
} as const;
