import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createTransactionalPostgresClient} from '../../shared/storage/transactional-postgres';import {createDeliveryPolicyRepository} from '../../features/notifications/delivery-policy-repository';
import {createNotificationCutoverMigration} from '../../features/notifications/notification-cutover-migration';
const url=process.env.ORBIT_EVENT_DATABASE_URL;
test('migration dry-run is zero-write, apply is scoped/idempotent, rollback retains receipts and user changes',{skip:!url},async()=>{
 const client=createTransactionalPostgresClient({connectionString:url!,max:2}),workspaceId='qa:cutover:'+randomUUID(),now=()=> '2026-09-16T01:00:00.000Z',repo=createDeliveryPolicyRepository({client,workspaceId,now}),migration=createNotificationCutoverMigration({client,workspaceId,now});
 try{await repo.tx('a',async db=>{await repo.save(db,'notifications','noise','a',{title:'Review follow-up for contact_42',evidenceIds:[]});await repo.save(db,'notificationDeliveries','pending','a',{delivery:{actorId:'a',status:'scheduled',phase:'pre_event',signalId:'event:1'}});await repo.save(db,'notificationDeliveries','sent','a',{delivery:{actorId:'a',status:'sent',providerReceiptId:'ticket'}});await repo.save(db,'reminderPlans','explicit','a',{entity:{id:'explicit',createdBy:'user',status:'scheduled',fireAt:'2026-09-17T01:00:00.000Z'}});await repo.save(db,'notification_interactions','read','a',{notificationId:'noise',state:'read'});await repo.save(db,'notifications','foreign','b',{title:'Review follow-up for contact_2'});});
 const count=async()=>Number((await client.query<{n:string}>('select count(*) as n from orbit_records where workspace_id=$1',[workspaceId])).rows[0].n);const before=await count(),plan=await migration.plan('a');assert.equal(await count(),before);assert.equal(plan.changes.length,2);assert.ok(plan.items.some(x=>x.legacyId==='noise'&&x.readState==='read'));assert.equal(plan.items.some(x=>x.legacyId==='foreign'),false);
 await assert.rejects(migration.apply('a','batch','wrong'));const result=await migration.apply('a','batch',plan.hash);assert.equal(result.state,'applied');assert.equal((await migration.apply('a','batch',plan.hash)).state,'applied');assert.equal((await repo.cutover('a'))?.enabled,true);
 assert.equal((await repo.get<{delivery:{status:string}}>(client,'notificationDeliveries','pending'))?.delivery.status,'suppressed');assert.equal((await repo.get<{entity:{status:string}}>(client,'reminderPlans','explicit'))?.entity.status,'scheduled');
 await repo.tx('a',db=>repo.save(db,'notificationDeliveries','pending','a',{delivery:{actorId:'a',status:'sent',providerReceiptId:'late-ticket'}}));
 const rolled=await migration.rollback('a','batch');assert.equal(rolled.state,'rolled_back');assert.ok(rolled.conflicts.includes('notificationDeliveries:pending'));assert.equal((await repo.get<{delivery:{providerReceiptId:string}}>(client,'notificationDeliveries','pending'))?.delivery.providerReceiptId,'late-ticket');assert.equal((await repo.cutover('a'))?.enabled,false);assert.equal((await migration.rollback('a','batch')).state,'rolled_back');
 }finally{await client.query('delete from orbit_records where workspace_id=$1',[workspaceId]);await client.close();}
});
