import test from 'node:test';
import assert from 'node:assert/strict';
import { createMemoryLiveRecordStore } from '../../shared/storage/live-record-store';
import { createDiscoverySourceAdapters } from '../../features/notifications/discovery/source-adapters';
import type { DiscoveryPreferences } from '../../features/notifications/discovery/contract';
const now='2026-09-16T00:00:00.000Z';
const preferences:DiscoveryPreferences={actorId:'a',enabled:true,messageAnalysisEnabled:true,timeZone:'Asia/Tokyo',language:'zh',revision:1,generation:1,enabledSince:'2026-09-15T00:00:00.000Z',messageEnabledSince:'2026-09-15T00:00:00.000Z',updatedAt:now};
async function fixture(){const store=createMemoryLiveRecordStore<Record<string,unknown>>();const write=async(collectionName:string,recordId:string,userId:string,payload:Record<string,unknown>)=>store.upsertRecord({workspaceId:'w',collectionName,recordId,userId,payload,sourceType:'manual',sourceId:recordId,evidenceIds:[],lifecycleState:'active',createdAt:now,updatedAt:now});const adapters=createDiscoverySourceAdapters({store,workspaceId:'w',client:{query:async()=>({rows:[]})},preferences:async()=>preferences,now:()=>now});return {store,write,adapters};}
test('notes are actor-owned, version-checked and minimal; local pending data is never a source',async()=>{const f=await fixture();await f.write('notes','n','a',{schemaVersion:2,operations:[],note:{id:'n',ownerUserId:'a',accountId:'a',title:'笔记',body:'我答应发送报价资料。',manualContactIds:[],mentions:[],contactIds:[],eventIds:[],version:2,createdAt:now,updatedAt:now,secret:'private-extra'}});const ref={kind:'note' as const,id:'n',revision:'2',at:now,key:'note:n'};const n=await f.adapters.read('a',ref);assert.equal(n?.text,'笔记\n我答应发送报价资料。');assert.equal(JSON.stringify(n).includes('private-extra'),false);assert.equal(await f.adapters.read('b',ref),null);assert.equal(await f.adapters.read('a',{...ref,revision:'1'}),null);assert.equal(await f.adapters.read('a',{...ref,id:'local-pending'}),null);});
test('message analysis requires explicit permission and current binding; author is the actual sender',async()=>{const f=await fixture();await f.write('contacts','c','a',{id:'c',displayName:'佐藤'});await f.write('relationship_communication_bindings','b','a',{bindingId:'b',conversationId:'v',status:'confirmed',inviterAccountId:'a',remoteAccountId:'other',contactId:'c',qualificationVersion:'q'});await f.write('relationship_communication_conversations','v','a',{bindingId:'b',conversationId:'v',contactId:'c',status:'active',participantDisplayNames:{a:'当前用户',other:'佐藤'},participantAccountIds:['a','other'],qualificationVersion:'q'});await f.write('relationship_communication_messages','m','other',{messageId:'m',conversationId:'v',body:'我会发送资料',senderAccountId:'other',senderDisplayName:'佐藤',sentAt:now,qualificationVersion:'q'});const ref={kind:'message' as const,id:'m',revision:now,at:now,key:'message:m'};const m=await f.adapters.read('a',ref);assert.equal(m?.authorId,'other');assert.equal(m?.source.authorId,'other');preferences.messageAnalysisEnabled=false;assert.equal(await f.adapters.read('a',ref),null);preferences.messageAnalysisEnabled=true;await f.write('relationship_communication_bindings','b','a',{status:'revoked'});assert.equal(await f.adapters.read('a',ref),null);});
test('completed tasks and unavailable external connectors never become fabricated evidence',async()=>{const f=await fixture();await f.write('tasks','t','a',{task:{id:'t',ownerUserId:'a',accountId:'a',title:'发送资料',status:'completed',updatedAt:now}});const t=await f.adapters.read('a',{kind:'task',id:'t',revision:now,at:now,key:'task:t'});assert.equal(t,null);assert.deepEqual(await f.adapters.externalAvailability('a'),{email:'unavailable',calendar:'unavailable'});});
