import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createTransactionalPostgresClient} from '../../shared/storage/transactional-postgres';import {createDeliveryPolicyRepository} from '../../features/notifications/delivery-policy-repository';import {createTypedDeliveryRuntime} from '../../features/notifications/typed-delivery-factory';
const url=process.env.ORBIT_EVENT_DATABASE_URL;
test('real storage sends a contact message with AI disabled, then suppresses read/revoked sources and fences legacy claims',{skip:!url},async()=>{
 const client=createTransactionalPostgresClient({connectionString:url!,max:4}),workspaceId='qa:typed-source:'+randomUUID(),now=()=> '2026-09-16T01:00:00.000Z',repo=createDeliveryPolicyRepository({client,workspaceId,now});
 const devices={listActive:async()=>[{deviceId:'d',token:'qa-not-a-provider-token',platform:'ios' as const,permission:'granted' as const,active:true,registeredAt:now(),updatedAt:now()}],revoke:async()=>null,register:async()=>{throw Error('not used');}};const calls:unknown[]=[];
 const runtime=createTypedDeliveryRuntime({client,workspaceId,actorId:'a',now,devices,push:{send:async request=>{calls.push(request);return {receiptId:'qa-ticket',verified:true};}}});
 try{await repo.tx('a',async db=>{await repo.save(db,'notificationCutover','a','a',{enabled:true,legacyBlocked:true,generation:1,since:'2026-09-16T00:00:00.000Z',batchId:'qa'});await repo.save(db,'relationship_communication_bindings','b','a',{status:'confirmed',conversationId:'c',contactId:'contact',qualificationVersion:'v1',inviterAccountId:'a',remoteAccountId:'b'});await repo.save(db,'relationship_communication_conversations','c','a',{status:'active',conversationId:'c',bindingId:'b',contactId:'contact',qualificationVersion:'v1',participantAccountIds:['a','b'],participantDisplayNames:{a:'Orbit QA',b:'佐藤健一'}});await repo.save(db,'relationship_communication_messages','m','b',{deliveryState:'delivered',messageId:'m',conversationId:'c',qualificationVersion:'v1',senderAccountId:'b',senderDisplayName:'佐藤健一',body:'报价资料已收到',sentAt:now()});});await repo.acknowledgeOwner('a','d',1,true);
 const base={signalId:'message:m',signalRevision:now(),phase:'commitment' as const,title:'Orbit',body:'Message',scheduledFor:now(),policySource:{kind:'message' as const,id:'m',eventKey:'m',conversationId:'c'}};
 const {delivery}=await runtime.ledger.materialize(base);const source=await runtime.sources.resolve(delivery);assert.equal(source?.title,'佐藤健一');assert.equal(source?.subject.read,false);
 assert.equal((await runtime.worker.run({workerId:'w'})).sent,1);assert.equal(calls.length,1);assert.deepEqual((calls[0] as {data:unknown}).data,{deliveryId:delivery.deliveryId});assert.equal((calls[0] as {body:string}).body,'你收到了一条新消息');
 await runtime.ledger.materialize({...base,signalId:'legacy',policySource:undefined} as never);assert.equal((await runtime.ledger.claimReady({workerId:'legacy',now:now(),limit:10})).length,0);
 await repo.tx('a',db=>repo.save(db,'relationship_communication_reads','r','a',{conversationId:'c',lastReadMessageId:'m'}));assert.equal((await runtime.sources.resolve(delivery))?.subject.read,true);
 await repo.tx('a',db=>repo.save(db,'relationship_communication_bindings','b','a',{status:'revoked'}));assert.equal(await runtime.sources.resolve(delivery),null);
 }finally{await client.query('delete from orbit_records where workspace_id=$1',[workspaceId]);await client.close();}
});
