import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {useOrbitAuthSession} from '../../api/AuthSessionProvider';
import {useOrbitApiBaseUrl} from '../../api/ApiBaseUrlProvider';
import {useOrbitLocale} from '../../i18n/OrbitLocaleContext';
import {useOrbitTheme} from '../../design/theme';
import {useInboxRequests} from '../inbox/RelationshipInboxScreen';
import type {InboxDeliveryPreferencesDTO,InboxDeliveryPreferencesInput} from '../../api/contract/notification-delivery-policy';
import {inboxDeliveryPreferencesSchema} from '../../api/schema/notification-delivery-policy';
const endpoint='/api/inbox/delivery/preferences';
const copy={zh:{title:'通知与消息',hint:'仅控制系统推送，收件箱仍会保留消息。自动通知每天最多 2 条，其中建议最多 1 条。',messageEnabled:'联系人消息',reminderEnabled:'提醒',suggestionEnabled:'建议',updateEnabled:'动态',quietHoursEnabled:'夜间静默（22:00–08:00）',preview:'锁屏显示消息内容',muted:'此会话免打扰',error:'未能确认设置，请刷新后重试。',refresh:'刷新设置',on:'开启',off:'关闭'},en:{title:'Notifications and messages',hint:'Controls system push. Messages remain in your inbox. At most 2 automatic notifications per day, including 1 suggestion.',messageEnabled:'Contact messages',reminderEnabled:'Reminders',suggestionEnabled:'Suggestions',updateEnabled:'Updates',quietHoursEnabled:'Quiet hours (22:00–08:00)',preview:'Show content on lock screen',muted:'Mute this conversation',error:'Could not confirm this setting. Refresh and retry.',refresh:'Refresh settings',on:'On',off:'Off'},ja:{title:'通知とメッセージ',hint:'システム通知を設定します。受信トレイの内容は残ります。自動通知は1日2件まで、うち提案は1件までです。',messageEnabled:'連絡先のメッセージ',reminderEnabled:'リマインダー',suggestionEnabled:'提案',updateEnabled:'更新',quietHoursEnabled:'夜間は通知しない（22:00–08:00）',preview:'ロック画面に内容を表示',muted:'この会話をミュート',error:'設定を確認できませんでした。更新して再試行してください。',refresh:'設定を更新',on:'オン',off:'オフ'}};
export function NotificationDeliverySettings({conversationId}:{conversationId?:string|undefined}){const auth=useOrbitAuthSession(),server=useOrbitApiBaseUrl();const scope=JSON.stringify([auth.actorId,auth.cookieHeader,server.baseUrl,conversationId]);return auth.ready&&auth.signedIn&&auth.actorId&&server.ready?<ScopedDeliverySettings key={scope} actorId={auth.actorId} scope={scope} conversationId={conversationId}/>:null;}
function ScopedDeliverySettings({actorId,scope,conversationId}:{actorId:string;scope:string;conversationId?:string|undefined}){
 const {language}=useOrbitLocale(),c=copy[language],{colors}=useOrbitTheme(),{clientGet,clientPost,isCurrent}=useInboxRequests(scope);
 const [snapshot,setSnapshot]=useState<{owner:typeof isCurrent;data:InboxDeliveryPreferencesDTO}|null>(null),[attempt,setAttempt]=useState(0),[error,setError]=useState(false),[busy,setBusy]=useState(false),[disabled,setDisabled]=useState(false);const lock=useRef(false);const data=isCurrent()&&snapshot?.owner===isCurrent?snapshot.data:null;
 const read=(raw:unknown)=>{const p=inboxDeliveryPreferencesSchema.safeParse(raw);return p.success&&p.data.actorId===actorId?p.data:null;};
 useEffect(()=>{const abort=new AbortController();setSnapshot(null);setBusy(false);setDisabled(false);lock.current=false;void clientGet(endpoint,{signal:abort.signal}).then(r=>{if(abort.signal.aborted||!isCurrent())return;if(!r.success&&r.status===404){setDisabled(true);return;}const next=r.success?read(r.data):null;if(next){setSnapshot({owner:isCurrent,data:next});setError(false);}else setError(true);}).catch(()=>{if(!abort.signal.aborted&&isCurrent())setError(true);});return()=>abort.abort();},[actorId,clientGet,isCurrent,attempt]);
 async function change(patch:Omit<InboxDeliveryPreferencesInput,'expectedRevision'>){if(!data||lock.current||!isCurrent())return;lock.current=true;setBusy(true);try{const r=await clientPost(endpoint,{...patch,expectedRevision:data.revision});if(!isCurrent())return;const next=r.success?read(r.data):null;if(next){setSnapshot({owner:isCurrent,data:next});setError(false);}else{setError(true);setAttempt(v=>v+1);}}catch{if(isCurrent())setError(true);}finally{if(isCurrent()){lock.current=false;setBusy(false);}}}
 if(disabled)return null;
 const rows=data?(conversationId?[{key:'muted',label:c.muted,on:data.mutedConversationIds.includes(conversationId),patch:()=>({muteConversation:{conversationId,muted:!data.mutedConversationIds.includes(conversationId)}})}]:[...(['messageEnabled','reminderEnabled','suggestionEnabled','updateEnabled','quietHoursEnabled'] as const).map(key=>({key,label:c[key],on:data[key],patch:()=>({[key]:!data[key]})})),{key:'preview',label:c.preview,on:data.lockScreenContent==='full',patch:()=>({lockScreenContent:data.lockScreenContent==='full'?'private' as const:'full' as const})}]):[];
 return <View style={{gap:10,paddingVertical:16,borderBottomWidth:1,borderBottomColor:colors.border}}>{!conversationId?<><Text accessibilityRole="header" style={{color:colors.text,fontSize:17,fontWeight:'600'}}>{c.title}</Text><Text style={{color:colors.text3,lineHeight:22}}>{c.hint}</Text></>:null}{rows.map(row=><Pressable key={row.key} accessibilityRole="switch" accessibilityLabel={row.label} accessibilityState={{checked:row.on,disabled:busy}} disabled={busy} onPress={()=>void change(row.patch())} style={{minHeight:48,flexDirection:'row',alignItems:'center',gap:12}}><Text style={{flex:1,color:colors.text,fontSize:15}}>{row.label}</Text><Text style={{color:colors.accent}}>{row.on?c.on:c.off}</Text></Pressable>)}{error?<Text accessibilityRole="alert" style={{color:colors.text}}>{c.error}</Text>:null}{!data||error?<Pressable onPress={()=>setAttempt(v=>v+1)} accessibilityRole="button" style={{minHeight:44,justifyContent:'center'}}><Text style={{color:colors.accent}}>{c.refresh}</Text></Pressable>:null}</View>;
}
