'use client';
import {useEffect,useRef,useState} from 'react';
import {useOrbitLanguage} from '../orbit-language-context';
import {readContactMessageActor} from '../inbox/contact-messages-tab';
import type {InboxDeliveryPreferencesDTO,InboxDeliveryPreferencesInput} from '../../../../shared/contract/notification-delivery-policy';
import {inboxDeliveryPreferencesSchema} from '../../../../shared/api-schema/notification-delivery-policy';
const endpoint='/api/inbox/delivery/preferences';
export function NotificationDeliverySettings({conversationId}:{conversationId?:string}){
 const {t,language}=useOrbitLanguage(),[data,setData]=useState<InboxDeliveryPreferencesDTO|null>(null),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false);const controller=useRef<AbortController|null>(null),lock=useRef(false);
 useEffect(()=>{const scope=new AbortController();controller.current=scope;setData(null);setError(false);setBusy(false);lock.current=false;void(async()=>{const actor=await readContactMessageActor(scope.signal);if(!actor)throw Error();const r=await fetch(endpoint,{signal:scope.signal,cache:'no-store'});if(r.status===404)return;const body=await r.json(),p=inboxDeliveryPreferencesSchema.safeParse(body.data);if(!r.ok||!p.success||p.data.actorId!==actor||await readContactMessageActor(scope.signal)!==actor)throw Error();if(!scope.signal.aborted)setData(p.data);})().catch(()=>{if(!scope.signal.aborted)setError(true);});const hide=()=>{if(document.visibilityState==='hidden'){scope.abort();setData(null);}else setAttempt(v=>v+1);};document.addEventListener('visibilitychange',hide);return()=>{scope.abort();document.removeEventListener('visibilitychange',hide);};},[attempt,language,conversationId]);
 async function change(patch:Omit<InboxDeliveryPreferencesInput,'expectedRevision'>){const scope=controller.current;if(!data||lock.current||!scope||scope.signal.aborted)return;lock.current=true;setBusy(true);try{if(await readContactMessageActor(scope.signal)!==data.actorId)throw Error();const r=await fetch(endpoint,{method:'PUT',signal:scope.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({...patch,expectedRevision:data.revision})});const body=await r.json(),p=inboxDeliveryPreferencesSchema.safeParse(body.data);if(!r.ok||!p.success||p.data.actorId!==data.actorId||await readContactMessageActor(scope.signal)!==data.actorId)throw Error();if(!scope.signal.aborted){setData(p.data);setError(false);}}catch{if(!scope.signal.aborted){setData(null);setError(true);}}finally{if(!scope.signal.aborted){lock.current=false;setBusy(false);}}}
 if(!data&&!error)return null;
 const rows=data?(conversationId?[{key:'muted',label:t({zh:'此会话免打扰',en:'Mute this conversation',ja:'この会話をミュート'}),on:data.mutedConversationIds.includes(conversationId),patch:()=>({muteConversation:{conversationId,muted:!data.mutedConversationIds.includes(conversationId)}})}]:[...(['messageEnabled','reminderEnabled','suggestionEnabled','updateEnabled','quietHoursEnabled'] as const).map(key=>({key,label:t({messageEnabled:{zh:'联系人消息',en:'Contact messages',ja:'連絡先のメッセージ'},reminderEnabled:{zh:'提醒',en:'Reminders',ja:'リマインダー'},suggestionEnabled:{zh:'建议',en:'Suggestions',ja:'提案'},updateEnabled:{zh:'动态',en:'Updates',ja:'更新'},quietHoursEnabled:{zh:'夜间静默（22:00–08:00）',en:'Quiet hours (22:00–08:00)',ja:'夜間は通知しない（22:00–08:00）'}}[key]),on:data[key],patch:()=>({[key]:!data[key]})})),{key:'preview',label:t({zh:'锁屏显示消息内容',en:'Show content on lock screen',ja:'ロック画面に内容を表示'}),on:data.lockScreenContent==='full',patch:()=>({lockScreenContent:data.lockScreenContent==='full'?'private' as const:'full' as const})}]):[];
 return <section style={{padding:'20px 0',borderBottom:'1px solid var(--border)'}}>{!conversationId?<><h3>{t({zh:'通知与消息',en:'Notifications and messages',ja:'通知とメッセージ'})}</h3><p>{t({zh:'仅控制系统推送，收件箱仍会保留消息。自动通知每天最多 2 条，其中建议最多 1 条。',en:'Controls system push. Messages remain in your inbox. At most 2 automatic notifications per day, including 1 suggestion.',ja:'システム通知を設定します。受信トレイの内容は残ります。自動通知は1日2件まで、うち提案は1件までです。'})}</p></>:null}{rows.map(row=><label key={row.key} style={{display:'flex',gap:16,alignItems:'center',padding:'14px 0'}}><span style={{flex:1}}>{row.label}</span><input type="checkbox" checked={row.on} disabled={busy} onChange={()=>void change(row.patch())} style={{width:20,height:20,minHeight:20}}/></label>)}{error?<><p role="alert">{t({zh:'未能确认设置，请刷新后重试。',en:'Could not confirm this setting. Refresh and retry.',ja:'設定を確認できませんでした。更新して再試行してください。'})}</p><button disabled={busy} onClick={()=>setAttempt(v=>v+1)}>{t({zh:'刷新设置',en:'Refresh settings',ja:'設定を更新'})}</button></>:null}</section>;
}
