import {
  ORBIT_AGENT_ARTIFACT_ERROR_DEFINITIONS,
  ORBIT_AGENT_ARTIFACT_FIXTURE_SOURCE,
  ORBIT_AGENT_ARTIFACT_KINDS,
  type OrbitAgentArtifactErrorCode,
  type OrbitAgentArtifactFailure,
  type OrbitAgentArtifactGeneratedView,
  type OrbitAgentArtifactKind,
  type OrbitAgentArtifactLookupInput,
  type OrbitAgentArtifactPayload,
  type OrbitAgentArtifactPresentation,
  type OrbitAgentArtifactProvenance,
  type OrbitAgentArtifactResult,
  type OrbitAgentArtifactResultEnvelope,
  type OrbitAgentArtifactScenario,
  type OrbitAgentArtifactSourceModule,
  type OrbitAgentArtifactStatus,
  type OrbitAgentArtifactSubAgent,
  type OrbitAgentArtifactSuccess,
  type OrbitAgentArtifactTask,
  type OrbitAgentArtifactTaskRequest,
  type OrbitAgentArtifactToolCallTrace,
} from "./artifact-contract";
import type { OrbitAgentArtifactTaskService } from "./service";

const fixtureNow = "2026-06-27T00:02:00.000Z";
const fixtureReadyAt = "2026-06-27T00:02:01.000Z";
const defaultConversationId = "demo-orbit-agent-conversation-1";
const defaultArtifactId = "artifact:event-recommendations:demo";
const defaultTaskId = "task:event-recommendations:demo";

const supportedKinds = new Set<string>(ORBIT_AGENT_ARTIFACT_KINDS);
const supportedScenarios = new Set<OrbitAgentArtifactScenario>([
  "ready",
  "pending",
  "failure",
]);

const safety = {
  actionsRequireConfirmation: true,
  aiProviderRequested: false,
  calendarProviderRequested: false,
  domainWritesExecuted: false,
  emailProviderRequested: false,
  externalNetworkRequested: false,
  externalSideEffectsExecuted: false,
  liveDatabaseReadExecuted: false,
  liveDatabaseWriteExecuted: false,
  notificationDelivered: false,
} as const;

function clonePayload<TPayload>(payload: TPayload): TPayload {
  return JSON.parse(JSON.stringify(payload)) as TPayload;
}

function readText(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function normalizeScenario(
  scenario?: OrbitAgentArtifactTaskRequest["scenario"],
): OrbitAgentArtifactScenario {
  if (scenario && supportedScenarios.has(scenario as OrbitAgentArtifactScenario)) {
    return scenario as OrbitAgentArtifactScenario;
  }

  return "ready";
}

function normalizeKind(kind: unknown): OrbitAgentArtifactKind | null {
  if (typeof kind === "string" && supportedKinds.has(kind)) {
    return kind as OrbitAgentArtifactKind;
  }

  return null;
}

function slugFor(kind: OrbitAgentArtifactKind): string {
  return kind.replace(/_/g, "-");
}

function artifactIdFor(kind: OrbitAgentArtifactKind): string {
  return `artifact:${slugFor(kind)}:demo`;
}

function taskIdFor(kind: OrbitAgentArtifactKind): string {
  return `task:${slugFor(kind)}:demo`;
}

function defaultSubAgentFor(
  kind: OrbitAgentArtifactKind,
): OrbitAgentArtifactSubAgent {
  switch (kind) {
    case "event_recommendations":
      return "event_recommendation_agent";
    case "contact_recommendations":
      return "contact_recommendation_agent";
    case "followup_queue":
      return "followup_review_agent";
    case "relationship_chat_context":
    case "email_context":
    case "generic":
    default:
      return "relationship_chat_review_agent";
  }
}

function sourceModulesFor(
  kind: OrbitAgentArtifactKind,
): readonly OrbitAgentArtifactSourceModule[] {
  switch (kind) {
    case "event_recommendations":
      return ["orbit-ai", "events"];
    case "contact_recommendations":
      return ["orbit-ai", "contacts"];
    case "followup_queue":
      return ["orbit-ai", "followups"];
    case "relationship_chat_context":
      return ["orbit-ai", "chat"];
    case "email_context":
      return ["orbit-ai", "chat", "contacts"];
    case "generic":
    default:
      return ["orbit-ai"];
  }
}

function presentationFor(
  kind: OrbitAgentArtifactKind,
  presentation?: Partial<OrbitAgentArtifactPresentation>,
): OrbitAgentArtifactPresentation {
  const defaults: Record<OrbitAgentArtifactKind, OrbitAgentArtifactPresentation> = {
    contact_recommendations: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the contact recommendation sub-agent mock",
      title: "Recommended contacts",
      widthHint: "half",
    },
    email_context: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the relationship chat review sub-agent mock",
      title: "Relevant email context",
      widthHint: "half",
    },
    event_recommendations: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the event recommendation sub-agent mock",
      title: "Recommended events",
      widthHint: "half",
    },
    followup_queue: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the follow-up review sub-agent mock",
      title: "Follow-up queue",
      widthHint: "half",
    },
    generic: {
      preferredSurface: "inline_card",
      subtitle: "Generated by the generic artifact sub-agent mock",
      title: "Agent artifact",
    },
    relationship_chat_context: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the relationship chat review sub-agent mock",
      title: "Relationship chat context",
      widthHint: "half",
    },
  };

  return {
    ...defaults[kind],
    ...presentation,
    title: presentation?.title?.trim() || defaults[kind].title,
  };
}

function evidenceIdsFor(kind: OrbitAgentArtifactKind): readonly string[] {
  return [`evidence:orbit-agent:${slugFor(kind)}:fixture`];
}

function toolNameFor(kind: OrbitAgentArtifactKind): string {
  switch (kind) {
    case "event_recommendations":
      return "events.recommend";
    case "contact_recommendations":
      return "contacts.recommend";
    case "followup_queue":
      return "followups.reviewQueue";
    case "relationship_chat_context":
      return "chat.context";
    case "email_context":
      return "chat.reviewEmailContext";
    case "generic":
    default:
      return "orbitAi.renderGenericArtifact";
  }
}

function toolTraceFor(
  kind: OrbitAgentArtifactKind,
  status: "completed" | "planned" | "failed",
): readonly OrbitAgentArtifactToolCallTrace[] {
  return [
    {
      evidenceIds: evidenceIdsFor(kind),
      reason:
        status === "planned"
          ? "The sub-agent task is registered but the mock has not produced a generated view yet."
          : "The mock sub-agent produced a traceable generated view without calling live providers.",
      status,
      toolCallId: `toolcall:${slugFor(kind)}:demo`,
      toolName: toolNameFor(kind),
    },
  ];
}

function provenanceFor(
  kind: OrbitAgentArtifactKind,
  status: OrbitAgentArtifactStatus,
): OrbitAgentArtifactProvenance {
  return {
    evidenceIds: evidenceIdsFor(kind),
    generatedAt: status === "pending" ? fixtureNow : fixtureReadyAt,
    generationMethod:
      status === "ready" ? "sub-agent-generated-view" : "rule-based-artifact-task",
    source: ORBIT_AGENT_ARTIFACT_FIXTURE_SOURCE,
    sourceModules: sourceModulesFor(kind),
    toolCalls: toolTraceFor(
      kind,
      status === "ready" ? "completed" : status === "failed" ? "failed" : "planned",
    ),
  };
}

function generatedViewFor(
  kind: OrbitAgentArtifactKind,
  query: string,
): OrbitAgentArtifactGeneratedView {
  switch (kind) {
    case "event_recommendations":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "event:review-founder-roundtable",
                    label: "Review event",
                    requiresConfirmation: true,
                  },
                ],
                body: "Small-format founder discussion with a high likelihood of useful introductions.",
                confidenceLabel: "High confidence",
                evidenceIds: evidenceIdsFor(kind),
                id: "event-founder-roundtable",
                metadata: [
                  { label: "When", value: "Next Thursday" },
                  { label: "Fit", value: "Founder and investor network" },
                ],
                reason: `Matches the request: ${query}`,
                subtitle: "Tokyo",
                title: "Founder relationship roundtable",
              },
            ],
            title: "Recommended events",
          },
        ],
        summary:
          "The event recommendation sub-agent found one high-fit event and prepared a side-panel view.",
      };
    case "contact_recommendations":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "contact:open-maya-chen",
                    label: "Review contact",
                    requiresConfirmation: true,
                  },
                ],
                body: "Strong overlap with the climate pilot and recent product partnership discussions.",
                confidenceLabel: "Medium confidence",
                evidenceIds: evidenceIdsFor(kind),
                id: "contact-maya-chen",
                metadata: [
                  { label: "Orbit", value: "1" },
                  { label: "Last touch", value: "2 weeks ago" },
                ],
                reason: `Relevant to the user request: ${query}`,
                subtitle: "Product partnerships",
                title: "Maya Chen",
              },
            ],
            title: "Recommended contacts",
          },
        ],
        summary:
          "The contact recommendation sub-agent selected one relationship to review before any outreach.",
      };
    case "followup_queue":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "followup:review-maya",
                    label: "Review follow-up",
                    requiresConfirmation: true,
                  },
                ],
                body: "Draft a short check-in that references the product partnership thread.",
                confidenceLabel: "Ready to review",
                evidenceIds: evidenceIdsFor(kind),
                id: "followup-maya-checkin",
                metadata: [
                  { label: "Due", value: "Today" },
                  { label: "Priority", value: "High" },
                ],
                reason: `Follow-up is aligned with: ${query}`,
                subtitle: "Maya Chen",
                title: "Partnership check-in",
              },
            ],
            title: "Suggested follow-ups",
          },
        ],
        summary:
          "The follow-up sub-agent prepared a review queue item without sending a message.",
      };
    case "relationship_chat_context":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "chat:review-context-maya",
                    label: "Review context",
                    requiresConfirmation: true,
                  },
                ],
                body: "Recent thread suggests a concise reply with one specific next step.",
                confidenceLabel: "Context available",
                evidenceIds: evidenceIdsFor(kind),
                id: "chat-context-maya",
                metadata: [
                  { label: "Thread", value: "Partnership planning" },
                  { label: "Tone", value: "Warm and direct" },
                ],
                reason: `Useful for answering: ${query}`,
                subtitle: "Relationship chat",
                title: "Reply context",
              },
            ],
            title: "Conversation context",
          },
        ],
        summary:
          "The relationship chat sub-agent prepared context for a reply, with no message sent.",
      };
    case "email_context":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "email:review-context-maya",
                    label: "Review email",
                    requiresConfirmation: true,
                  },
                ],
                body: "The latest email asks for timing and a single owner for the next discussion.",
                confidenceLabel: "Relevant",
                evidenceIds: evidenceIdsFor(kind),
                id: "email-context-maya",
                metadata: [
                  { label: "Source", value: "Mock email summary" },
                  { label: "Age", value: "3 days" },
                ],
                reason: `Email context supports: ${query}`,
                subtitle: "Email context",
                title: "Recent planning email",
              },
            ],
            title: "Relevant emails",
          },
        ],
        summary:
          "The relationship chat sub-agent summarized relevant email context for side-panel review.",
      };
    case "generic":
    default:
      return {
        sections: [
          {
            items: [],
            title: "No domain artifact selected",
          },
        ],
        summary: `The generic artifact mock captured the request: ${query}`,
      };
  }
}

function taskFor(input: {
  conversationId?: string | null;
  kind: OrbitAgentArtifactKind;
  presentation: OrbitAgentArtifactPresentation;
  query: string;
  status: OrbitAgentArtifactStatus;
  subAgent?: OrbitAgentArtifactSubAgent;
}): OrbitAgentArtifactTask {
  return {
    artifactId: artifactIdFor(input.kind),
    conversationId: readText(input.conversationId) ?? defaultConversationId,
    createdAt: fixtureNow,
    kind: input.kind,
    presentation: input.presentation,
    query: input.query,
    status: input.status,
    subAgent: input.subAgent ?? defaultSubAgentFor(input.kind),
    taskId: taskIdFor(input.kind),
    updatedAt: input.status === "pending" ? fixtureNow : fixtureReadyAt,
  };
}

function resultFor(
  task: OrbitAgentArtifactTask,
  status: OrbitAgentArtifactStatus,
): OrbitAgentArtifactResult {
  return {
    artifactId: task.artifactId,
    generatedView:
      status === "ready" ? generatedViewFor(task.kind, task.query) : null,
    kind: task.kind,
    nextAction:
      status === "ready"
        ? "Render the generated artifact and require user confirmation before executing any action."
        : "Keep the artifact surface in a loading state; do not execute tools or external actions.",
    presentation: task.presentation,
    provenance: provenanceFor(task.kind, status),
    safety,
    status,
    taskId: task.taskId,
  };
}

function success(payload: OrbitAgentArtifactPayload): OrbitAgentArtifactSuccess {
  return {
    data: clonePayload(payload),
    success: true,
  };
}

function failure(
  code: OrbitAgentArtifactErrorCode,
  input?: { artifactId?: string; taskId?: string },
): OrbitAgentArtifactFailure {
  const definition = ORBIT_AGENT_ARTIFACT_ERROR_DEFINITIONS[code];

  return {
    error: {
      ...definition,
      artifactId: input?.artifactId,
      evidenceIds: ["evidence:orbit-agent:artifact-controlled-failure"],
      state: "failure",
      taskId: input?.taskId,
    },
    success: false,
  };
}

function payloadFor(input: {
  conversationId?: string | null;
  kind: OrbitAgentArtifactKind;
  presentation?: Partial<OrbitAgentArtifactPresentation>;
  query: string;
  status: OrbitAgentArtifactStatus;
  subAgent?: OrbitAgentArtifactSubAgent;
}): OrbitAgentArtifactPayload {
  const presentation = presentationFor(input.kind, input.presentation);
  const task = taskFor({
    conversationId: input.conversationId,
    kind: input.kind,
    presentation,
    query: input.query,
    status: input.status,
    subAgent: input.subAgent,
  });

  return {
    result: resultFor(task, input.status),
    task,
  };
}

function payloadForLookup(
  input: OrbitAgentArtifactLookupInput,
  status: OrbitAgentArtifactStatus,
): OrbitAgentArtifactResultEnvelope {
  const artifactId = readText(input.artifactId);

  if (!artifactId) {
    return failure("ORBIT_AGENT_ARTIFACT_NOT_FOUND");
  }

  const kind = ORBIT_AGENT_ARTIFACT_KINDS.find(
    (candidate) => artifactId === artifactIdFor(candidate),
  );

  if (!kind) {
    return failure("ORBIT_AGENT_ARTIFACT_NOT_FOUND", { artifactId });
  }

  return success(
    payloadFor({
      kind,
      query: `Lookup generated artifact ${artifactId}`,
      status,
    }),
  );
}

export function createMockOrbitAgentArtifactTaskService(): OrbitAgentArtifactTaskService {
  return {
    createArtifactTask(input): OrbitAgentArtifactResultEnvelope {
      const scenario = normalizeScenario(input.scenario);

      if (scenario === "failure") {
        return failure("ORBIT_AGENT_ARTIFACT_MOCK_FAILED");
      }

      const query = readText(input.query);

      if (!query) {
        return failure("ORBIT_AGENT_ARTIFACT_QUERY_REQUIRED");
      }

      const kind = normalizeKind(input.kind);

      if (!kind) {
        return failure("ORBIT_AGENT_ARTIFACT_UNSUPPORTED_KIND");
      }

      return success(
        payloadFor({
          conversationId: input.conversationId,
          kind,
          presentation: input.presentation,
          query,
          status: scenario === "pending" ? "pending" : "ready",
          subAgent: input.subAgent,
        }),
      );
    },

    getArtifactTask(input): OrbitAgentArtifactResultEnvelope {
      const scenario = normalizeScenario(input.scenario);

      if (scenario === "failure") {
        return failure("ORBIT_AGENT_ARTIFACT_MOCK_FAILED", {
          artifactId: readText(input.artifactId) ?? undefined,
        });
      }

      return payloadForLookup(
        input,
        scenario === "pending" ? "pending" : "ready",
      );
    },
  };
}
