import {
  ORBIT_AGENT_ARTIFACT_ERROR_DEFINITIONS,
  ORBIT_AGENT_ARTIFACT_KINDS,
  type OrbitAgentArtifactErrorCode,
  type OrbitAgentArtifactFailure,
  type OrbitAgentArtifactGeneratedView,
  type OrbitAgentArtifactKind,
  type OrbitAgentArtifactLookupInput,
  type OrbitAgentArtifactPayload,
  type OrbitAgentArtifactPresentation,
  type OrbitAgentArtifactProvenance,
  type OrbitAgentArtifactResult,
  type OrbitAgentArtifactResultEnvelope,
  type OrbitAgentArtifactScenario,
  type OrbitAgentArtifactSourceModule,
  type OrbitAgentArtifactStatus,
  type OrbitAgentArtifactProducer,
  type OrbitAgentArtifactSuccess,
  type OrbitAgentArtifactTask,
  type OrbitAgentArtifactTaskRequest,
  type OrbitAgentArtifactToolCallTrace,
} from "./artifact-contract";
import type { OrbitAgentArtifactTaskService } from "./service";

export const ORBIT_AGENT_ARTIFACT_FIXTURE_SOURCE =
  "fixture:features/orbit-ai/mock-artifact-task-service.ts" as const;

const fixtureNow = "2026-06-27T00:02:00.000Z";
const fixtureReadyAt = "2026-06-27T00:02:01.000Z";
const defaultConversationId = "demo-orbit-agent-conversation-1";
const defaultArtifactId = "artifact:event-recommendations:demo";
const defaultTaskId = "task:event-recommendations:demo";

// mock artifact service 模拟“artifact producer 生成可复核 artifact”的过程。
// 它不会调用真实工具、数据库或外部服务，只根据 kind/query 生成稳定 fixture payload。
const supportedKinds = new Set<string>(ORBIT_AGENT_ARTIFACT_KINDS);
const supportedScenarios = new Set<OrbitAgentArtifactScenario>([
  "ready",
  "pending",
  "failure",
]);

const safety = {
  actionsRequireConfirmation: true,
  aiProviderRequested: false,
  calendarProviderRequested: false,
  domainWritesExecuted: false,
  emailProviderRequested: false,
  externalNetworkRequested: false,
  externalSideEffectsExecuted: false,
  liveDatabaseReadExecuted: false,
  liveDatabaseWriteExecuted: false,
  notificationDelivered: false,
} as const;

function clonePayload<TPayload>(payload: TPayload): TPayload {
  // 返回前 clone，避免调用方修改共享 fixture。
  return JSON.parse(JSON.stringify(payload)) as TPayload;
}

function readText(value: unknown): string | null {
  // 所有文本入口统一 trim；空字符串按缺失处理。
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function normalizeScenario(
  scenario?: OrbitAgentArtifactTaskRequest["scenario"],
): OrbitAgentArtifactScenario {
  if (scenario && supportedScenarios.has(scenario as OrbitAgentArtifactScenario)) {
    return scenario as OrbitAgentArtifactScenario;
  }

  return "ready";
}

function normalizeKind(kind: unknown): OrbitAgentArtifactKind | null {
  // kind 必须来自 artifact contract 白名单，避免模型/调用方发明新 artifact 类型。
  if (typeof kind === "string" && supportedKinds.has(kind)) {
    return kind as OrbitAgentArtifactKind;
  }

  return null;
}

function slugFor(kind: OrbitAgentArtifactKind): string {
  return kind.replace(/_/g, "-");
}

function artifactIdFor(kind: OrbitAgentArtifactKind): string {
  return `artifact:${slugFor(kind)}:demo`;
}

function taskIdFor(kind: OrbitAgentArtifactKind): string {
  return `task:${slugFor(kind)}:demo`;
}

function defaultArtifactProducerFor(
  kind: OrbitAgentArtifactKind,
): OrbitAgentArtifactProducer {
  // kind 到 artifact producer 的映射是 UI trace 和 artifact 面板解释执行链的基础。
  switch (kind) {
    case "event_recommendations":
      return "event_recommendation_producer";
    case "contact_recommendations":
      return "contact_recommendation_producer";
    case "followup_queue":
      return "followup_review_producer";
    case "relationship_chat_context":
    case "email_context":
    case "generic":
    default:
      return "relationship_chat_review_producer";
  }
}

function sourceModulesFor(
  kind: OrbitAgentArtifactKind,
): readonly OrbitAgentArtifactSourceModule[] {
  // sourceModules 告诉 UI 这个 artifact 概念上来自哪些 Orbit 模块。
  switch (kind) {
    case "event_recommendations":
      return ["orbit-ai", "events"];
    case "contact_recommendations":
      return ["orbit-ai", "contacts"];
    case "followup_queue":
      return ["orbit-ai", "followups"];
    case "relationship_chat_context":
      return ["orbit-ai", "chat"];
    case "email_context":
      return ["orbit-ai", "chat", "contacts"];
    case "generic":
    default:
      return ["orbit-ai"];
  }
}

function presentationFor(
  kind: OrbitAgentArtifactKind,
  presentation?: Partial<OrbitAgentArtifactPresentation>,
): OrbitAgentArtifactPresentation {
  // 每类 artifact 有默认展示面；调用方可以覆盖标题/宽度等 presentation 字段。
  const defaults: Record<OrbitAgentArtifactKind, OrbitAgentArtifactPresentation> = {
    contact_recommendations: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the contact recommendation artifact producer mock",
      title: "Recommended contacts",
      widthHint: "half",
    },
    email_context: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the relationship chat review artifact producer mock",
      title: "Relevant email context",
      widthHint: "half",
    },
    event_recommendations: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the event recommendation artifact producer mock",
      title: "Recommended events",
      widthHint: "half",
    },
    followup_queue: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the follow-up review artifact producer mock",
      title: "Follow-up queue",
      widthHint: "half",
    },
    generic: {
      preferredSurface: "inline_card",
      subtitle: "Generated by the generic artifact producer mock",
      title: "Agent artifact",
    },
    relationship_chat_context: {
      preferredSurface: "side_panel",
      subtitle: "Generated by the relationship chat review artifact producer mock",
      title: "Relationship chat context",
      widthHint: "half",
    },
  };

  return {
    ...defaults[kind],
    ...presentation,
    title: presentation?.title?.trim() || defaults[kind].title,
  };
}

function evidenceIdsFor(kind: OrbitAgentArtifactKind): readonly string[] {
  return [`evidence:orbit-agent:${slugFor(kind)}:fixture`];
}

function toolNameFor(kind: OrbitAgentArtifactKind): string {
  switch (kind) {
    case "event_recommendations":
      return "events.recommend";
    case "contact_recommendations":
      return "contacts.recommend";
    case "followup_queue":
      return "followups.reviewQueue";
    case "relationship_chat_context":
      return "chat.context";
    case "email_context":
      return "chat.reviewEmailContext";
    case "generic":
    default:
      return "orbitAi.renderGenericArtifact";
  }
}

function toolTraceFor(
  kind: OrbitAgentArtifactKind,
  status: "completed" | "planned" | "failed",
): readonly OrbitAgentArtifactToolCallTrace[] {
  // tool trace 只记录 mock artifact producer 的计划/完成状态，不表示真实外部工具被调用。
  return [
    {
      evidenceIds: evidenceIdsFor(kind),
      reason:
        status === "planned"
          ? "The artifact producer task is registered but the mock has not produced a generated view yet."
          : "The mock artifact producer produced a traceable generated view without calling live providers.",
      status,
      toolCallId: `toolcall:${slugFor(kind)}:demo`,
      toolName: toolNameFor(kind),
    },
  ];
}

function provenanceFor(
  kind: OrbitAgentArtifactKind,
  status: OrbitAgentArtifactStatus,
): OrbitAgentArtifactProvenance {
  return {
    evidenceIds: evidenceIdsFor(kind),
    generatedAt: status === "pending" ? fixtureNow : fixtureReadyAt,
    generationMethod:
      status === "ready" ? "artifact-producer-generated-view" : "rule-based-artifact-task",
    source: ORBIT_AGENT_ARTIFACT_FIXTURE_SOURCE,
    sourceModules: sourceModulesFor(kind),
    toolCalls: toolTraceFor(
      kind,
      status === "ready" ? "completed" : status === "failed" ? "failed" : "planned",
    ),
  };
}

function generatedViewFor(
  kind: OrbitAgentArtifactKind,
  query: string,
): OrbitAgentArtifactGeneratedView {
  // generatedView 是给前端渲染的 pretty artifact；每个 action 都保留 confirmation 要求。
  switch (kind) {
    case "event_recommendations":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "event:review-founder-roundtable",
                    label: "Review event",
                    requiresConfirmation: true,
                  },
                ],
                body: "Small-format founder discussion with a high likelihood of useful introductions.",
                confidenceLabel: "High confidence",
                evidenceIds: evidenceIdsFor(kind),
                id: "event-founder-roundtable",
                metadata: [
                  { label: "When", value: "Next Thursday" },
                  { label: "Fit", value: "Founder and investor network" },
                ],
                reason: `Matches the request: ${query}`,
                subtitle: "Tokyo",
                title: "Founder relationship roundtable",
              },
            ],
            title: "Recommended events",
          },
        ],
        summary:
          "The event recommendation artifact producer found one high-fit event and prepared a side-panel view.",
      };
    case "contact_recommendations":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "contact:open-maya-chen",
                    label: "Review contact",
                    requiresConfirmation: true,
                  },
                ],
                body: "Strong overlap with the climate pilot and recent product partnership discussions.",
                confidenceLabel: "Medium confidence",
                evidenceIds: evidenceIdsFor(kind),
                id: "contact-maya-chen",
                metadata: [
                  { label: "Orbit", value: "1" },
                  { label: "Last touch", value: "2 weeks ago" },
                ],
                reason: `Relevant to the user request: ${query}`,
                subtitle: "Product partnerships",
                title: "Maya Chen",
              },
            ],
            title: "Recommended contacts",
          },
        ],
        summary:
          "The contact recommendation artifact producer selected one relationship to review before any outreach.",
      };
    case "followup_queue":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "followup:review-maya",
                    label: "Review follow-up",
                    requiresConfirmation: true,
                  },
                ],
                body: "Draft a short check-in that references the product partnership thread.",
                confidenceLabel: "Ready to review",
                evidenceIds: evidenceIdsFor(kind),
                id: "followup-maya-checkin",
                metadata: [
                  { label: "Due", value: "Today" },
                  { label: "Priority", value: "High" },
                ],
                reason: `Follow-up is aligned with: ${query}`,
                subtitle: "Maya Chen",
                title: "Partnership check-in",
              },
            ],
            title: "Suggested follow-ups",
          },
        ],
        summary:
          "The follow-up artifact producer prepared a review queue item without sending a message.",
      };
    case "relationship_chat_context":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "chat:review-context-maya",
                    label: "Review context",
                    requiresConfirmation: true,
                  },
                ],
                body: "Recent thread suggests a concise reply with one specific next step.",
                confidenceLabel: "Context available",
                evidenceIds: evidenceIdsFor(kind),
                id: "chat-context-maya",
                metadata: [
                  { label: "Thread", value: "Partnership planning" },
                  { label: "Tone", value: "Warm and direct" },
                ],
                reason: `Useful for answering: ${query}`,
                subtitle: "Relationship chat",
                title: "Reply context",
              },
            ],
            title: "Conversation context",
          },
        ],
        summary:
          "The relationship chat artifact producer prepared context for a reply, with no message sent.",
      };
    case "email_context":
      return {
        sections: [
          {
            items: [
              {
                actions: [
                  {
                    actionId: "email:review-context-maya",
                    label: "Review email",
                    requiresConfirmation: true,
                  },
                ],
                body: "The latest email asks for timing and a single owner for the next discussion.",
                confidenceLabel: "Relevant",
                evidenceIds: evidenceIdsFor(kind),
                id: "email-context-maya",
                metadata: [
                  { label: "Source", value: "Mock email summary" },
                  { label: "Age", value: "3 days" },
                ],
                reason: `Email context supports: ${query}`,
                subtitle: "Email context",
                title: "Recent planning email",
              },
            ],
            title: "Relevant emails",
          },
        ],
        summary:
          "The relationship chat artifact producer summarized relevant email context for side-panel review.",
      };
    case "generic":
    default:
      return {
        sections: [
          {
            items: [],
            title: "No domain artifact selected",
          },
        ],
        summary: `The generic artifact mock captured the request: ${query}`,
      };
  }
}

function taskFor(input: {
  conversationId?: string | null;
  kind: OrbitAgentArtifactKind;
  presentation: OrbitAgentArtifactPresentation;
  query: string;
  status: OrbitAgentArtifactStatus;
  artifactProducer?: OrbitAgentArtifactProducer;
}): OrbitAgentArtifactTask {
  return {
    artifactId: artifactIdFor(input.kind),
    conversationId: readText(input.conversationId) ?? defaultConversationId,
    createdAt: fixtureNow,
    kind: input.kind,
    presentation: input.presentation,
    query: input.query,
    status: input.status,
    artifactProducer: input.artifactProducer ?? defaultArtifactProducerFor(input.kind),
    taskId: taskIdFor(input.kind),
    updatedAt: input.status === "pending" ? fixtureNow : fixtureReadyAt,
  };
}

function resultFor(
  task: OrbitAgentArtifactTask,
  status: OrbitAgentArtifactStatus,
): OrbitAgentArtifactResult {
  // pending artifact 不产生 generatedView，只给 UI loading/nextAction 状态。
  return {
    artifactId: task.artifactId,
    generatedView:
      status === "ready" ? generatedViewFor(task.kind, task.query) : null,
    kind: task.kind,
    nextAction:
      status === "ready"
        ? "Render the generated artifact and require user confirmation before executing any action."
        : "Keep the artifact surface in a loading state; do not execute tools or external actions.",
    presentation: task.presentation,
    provenance: provenanceFor(task.kind, status),
    safety,
    status,
    taskId: task.taskId,
  };
}

function success(payload: OrbitAgentArtifactPayload): OrbitAgentArtifactSuccess {
  return {
    data: clonePayload(payload),
    success: true,
  };
}

function failure(
  code: OrbitAgentArtifactErrorCode,
  input?: { artifactId?: string; taskId?: string },
): OrbitAgentArtifactFailure {
  const definition = ORBIT_AGENT_ARTIFACT_ERROR_DEFINITIONS[code];

  return {
    error: {
      ...definition,
      artifactId: input?.artifactId,
      evidenceIds: ["evidence:orbit-agent:artifact-controlled-failure"],
      state: "failure",
      taskId: input?.taskId,
    },
    success: false,
  };
}

function payloadFor(input: {
  conversationId?: string | null;
  kind: OrbitAgentArtifactKind;
  presentation?: Partial<OrbitAgentArtifactPresentation>;
  query: string;
  status: OrbitAgentArtifactStatus;
  artifactProducer?: OrbitAgentArtifactProducer;
}): OrbitAgentArtifactPayload {
  const presentation = presentationFor(input.kind, input.presentation);
  const task = taskFor({
    conversationId: input.conversationId,
    kind: input.kind,
    presentation,
    query: input.query,
    status: input.status,
    artifactProducer: input.artifactProducer,
  });

  return {
    result: resultFor(task, input.status),
    task,
  };
}

function payloadForLookup(
  input: OrbitAgentArtifactLookupInput,
  status: OrbitAgentArtifactStatus,
): OrbitAgentArtifactResultEnvelope {
  const artifactId = readText(input.artifactId);

  // lookup 必须能从 artifactId 反推出已支持 kind，否则返回 not found。
  if (!artifactId) {
    return failure("ORBIT_AGENT_ARTIFACT_NOT_FOUND");
  }

  const kind = ORBIT_AGENT_ARTIFACT_KINDS.find(
    (candidate) => artifactId === artifactIdFor(candidate),
  );

  if (!kind) {
    return failure("ORBIT_AGENT_ARTIFACT_NOT_FOUND", { artifactId });
  }

  return success(
    payloadFor({
      kind,
      query: `Lookup generated artifact ${artifactId}`,
      status,
    }),
  );
}

export function createMockOrbitAgentArtifactTaskService(): OrbitAgentArtifactTaskService {
  return {
    createArtifactTask(input): OrbitAgentArtifactResultEnvelope {
      // create 路径先处理场景，再校验 query/kind，最后生成 ready 或 pending payload。
      const scenario = normalizeScenario(input.scenario);

      if (scenario === "failure") {
        return failure("ORBIT_AGENT_ARTIFACT_MOCK_FAILED");
      }

      const query = readText(input.query);

      if (!query) {
        return failure("ORBIT_AGENT_ARTIFACT_QUERY_REQUIRED");
      }

      const kind = normalizeKind(input.kind);

      if (!kind) {
        return failure("ORBIT_AGENT_ARTIFACT_UNSUPPORTED_KIND");
      }

      return success(
        payloadFor({
          conversationId: input.conversationId,
          kind,
          presentation: input.presentation,
          query,
          status: scenario === "pending" ? "pending" : "ready",
          artifactProducer: input.artifactProducer,
        }),
      );
    },

    getArtifactTask(input): OrbitAgentArtifactResultEnvelope {
      // get 路径按 artifactId 回放同一类 mock payload，方便 UI 详情页/调试页复用。
      const scenario = normalizeScenario(input.scenario);

      if (scenario === "failure") {
        return failure("ORBIT_AGENT_ARTIFACT_MOCK_FAILED", {
          artifactId: readText(input.artifactId) ?? undefined,
        });
      }

      return payloadForLookup(
        input,
        scenario === "pending" ? "pending" : "ready",
      );
    },
  };
}
