/**
 * R23 業界の現状ライブラリ（D-06，DESIGN §6）：内容即代码。初版（C6）只能引用这里 `published` 且 12 个月内核对过的条目。
 *
 * - 每条都有可查证的公开出处（官方统计、公的机关资料、研究机构的公开调查）；没有可靠出处的不收录，不编数字。
 * - 要点只写出处能支持的事实，并保留数据年份、统计口径（分母、样本范围）；推论不写进条目。
 * - 改内容 = 加一个新版本（`version` + 1），旧版本保留（已引用它的计划仍能显示当时那一版）。
 * - 审核：按 Q7 交 Codex 只读核对事实、出处、日期与三语；结论与处理记录在同目录 REVIEW.md，审核通过才 `published`。
 * - `updatedOn` = 编辑部最后核对这条的日期（12 个月规则看它）；`source.publishedOn` = 出处本身的发布日期。
 */
import type { LandscapeEntry } from "./types";

export const LANDSCAPE_ENTRIES: readonly LandscapeEntry[] = [
  {
    goalKinds: ["fundraising"],
    id: "L-101",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "スピーダ「2024年スタートアップ調達額は安定 ファンド設立に新局面」（Japan Startup Finance 2024 要約記事）", publishedOn: "2025-01-20", url: "https://initial.inc/articles/japan-startup-finance-2024" },
    status: "published",
    summary: {
      en: "Japanese startups raised about ¥779.3 billion in 2024 (excluding debt), 3% more than the 2023 full-year total as tallied at the same point a year earlier; about ¥310 million per company on average.",
      ja: "2024 年の国内スタートアップの資金調達額は約 7,793 億円（デット除く・集計時点の値）で、前年の同じ時点の集計より 3% 増えました。1 社あたりの平均は約 3.1 億円です。",
      zh: "2024 年日本初创企业融资额约 7,793 亿日元（不含债务，按统计时点的数值），比上一年同一时点的统计多 3%；每家平均约 3.1 亿日元。",
    },
    title: { en: "Startup funding in Japan, 2024", ja: "国内スタートアップの資金調達（2024 年）", zh: "日本初创企业融资（2024 年）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "1ef2a227c998c9b0",
  },
  {
    goalKinds: ["fundraising", "partnership"],
    id: "L-102",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "「CVC による出資の先に何が起きているのか、スタートアップとの事業連携の実態」（みずほ）", publishedOn: "2026-09-09", url: "https://www.mizuhobank.co.jp/corporate/mhri/consulting/articles-2026-k0031/index.html" },
    status: "published",
    summary: {
      en: "Corporate venture capital funds made up about 36% of the total amount of venture funds set up in Japan in 2024.",
      ja: "2024 年に国内で設立された VC ファンドの総額のうち、事業会社系（CVC）ファンドは約 36% を占めました。",
      zh: "2024 年日本新设风险投资基金的总额中，企业系（CVC）基金约占 36%。",
    },
    title: { en: "Share of corporate venture capital", ja: "事業会社系ファンド（CVC）の比重", zh: "企业风险投资（CVC）的比重" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "cca7329917c429cb",
  },
  {
    goalKinds: ["fundraising", "launch"],
    id: "L-103",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "日本政策金融公庫 総合研究所「2025 年度 新規開業実態調査」", publishedOn: "2025-12-05", url: "https://www.jfc.go.jp/n/findings/pdf/kaigyo_251205_1.pdf" },
    status: "published",
    summary: {
      en: "Among responding businesses that the Japan Finance Corporation lent to in April–September 2024 and that were no more than one year old when financed (excluding real-estate leasing), founders raised ¥12.19 million on average at start; 67.9% of that amount came from loans by financial institutions and others.",
      ja: "日本政策金融公庫が 2024 年 4〜9 月に融資し、融資時点で開業後 1 年以内だった回答企業（不動産賃貸業を除く）では、開業時の資金調達額は平均 1,219 万円で、その金額の 67.9% が金融機関などからの借入れでした。",
      zh: "日本政策金融公库于 2024 年 4–9 月贷款、贷款时开业不超过一年的受访企业（不含不动产租赁业），开业时平均筹资 1,219 万日元，其中金额的 67.9% 来自金融机构等的借款。",
    },
    title: { en: "How new businesses are funded", ja: "開業時の資金の集め方", zh: "开业资金从哪里来" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "57d05803fb6f140f",
  },
  {
    goalKinds: ["launch", "career"],
    id: "L-201",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "日本政策金融公庫 総合研究所「2025 年度 起業と起業意識に関する調査」", publishedOn: "2026-02-10", url: "https://www.jfc.go.jp/n/findings/pdf/kigyouishiki_260210_1.pdf" },
    status: "published",
    summary: {
      en: "Among respondents who started a business in 2021–2025, 78.0% of entrepreneurs (35+ hours a week on the business) and 76.5% of part-time entrepreneurs (under 35 hours) run it on their own (FY2025 survey).",
      ja: "2021〜2025 年に起業した回答者のうち、事業に週 35 時間以上を使う「起業家」の 78.0%、週 35 時間未満の「パートタイム起業家」の 76.5% が、本人だけで事業を運営しています（2025 年度調査）。",
      zh: "2021–2025 年创业的受访者中，每周投入事业 35 小时以上的「创业者」有 78.0%、不足 35 小时的「兼职创业者」有 76.5% 由本人独自经营（2025 年度调查）。",
    },
    title: { en: "Most founders work alone", ja: "起業家の多くは一人で運営", zh: "多数创业者独自经营" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "22f5a304f94f5642",
  },
  {
    goalKinds: ["launch", "sales"],
    id: "L-202",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "経済産業省「令和6年度電子商取引に関する市場調査の結果を取りまとめました」", publishedOn: "2025-08-26", url: "https://www.meti.go.jp/press/2025/08/20250826005/20250826005.html" },
    status: "published",
    summary: {
      en: "Japan's B2B e-commerce market reached about ¥514 trillion in 2024 (up 10.6%); excluding the survey's \"other\" category, 43.1% of B2B transaction value went through e-commerce, including EDI.",
      ja: "2024 年の国内 BtoB-EC 市場は約 514 兆円（前年比 10.6% 増）。調査分類の「その他」を除いた取引金額ベースの EC 化率は 43.1% でした（EDI を含みます）。",
      zh: "2024 年日本企业间电商（BtoB-EC）市场约 514 万亿日元（同比增长 10.6%）；排除调查分类中的「其他」后，按交易金额计算的电商化率为 43.1%（含 EDI）。",
    },
    title: { en: "B2B e-commerce in Japan, 2024", ja: "企業間取引の EC 化（2024 年）", zh: "企业间交易的电商化（2024 年）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "8fcc81bc423f6b6c",
  },
  {
    goalKinds: ["sales", "launch"],
    id: "L-203",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "中小企業庁「中小企業・小規模事業者の数（2021 年 6 月時点）の集計結果」", publishedOn: "2023-12-13", url: "https://www.chusho.meti.go.jp/koukai/chousa/chu_kigyocnt/2023/231213chukigyocnt.html" },
    status: "published",
    summary: {
      en: "Japan has about 3.365 million small and medium enterprises, 99.7% of all enterprises (June 2021, counting sole proprietors).",
      ja: "国内の中小企業は約 336.5 万者で、企業全体の 99.7% を占めます（2021 年 6 月時点、個人事業者を含む数）。",
      zh: "日本中小企业约 336.5 万家，占全部企业的 99.7%（2021 年 6 月，含个体经营者的家数）。",
    },
    title: { en: "99.7% of enterprises in Japan are SMEs", ja: "国内企業の 99.7% は中小企業", zh: "日本 99.7% 的企业是中小企业" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "9ae28985713c2206",
  },
  {
    goalKinds: ["sales", "launch"],
    id: "L-302",
    industries: [],
    reviewedBy: null,
    source: { label: "総務省「令和 5 年 通信利用動向調査の結果」", publishedOn: "2024-06-07", url: "https://www.soumu.go.jp/menu_news/s-news/01tsushin02_02000169.html" },
    status: "draft",
    summary: {
      en: "About 80% (77.7%) of Japanese companies with 100 or more employees use cloud services (2023 survey).",
      ja: "従業員 100 人以上の企業の約 8 割（77.7%）がクラウドサービスを利用しています（2023 年調査）。",
      zh: "日本员工 100 人以上的企业约八成（77.7%）在使用云服务（2023 年调查）。",
    },
    title: { en: "Cloud use at companies with 100+ staff", ja: "従業員 100 人以上の企業のクラウド利用", zh: "员工 100 人以上企业的云服务使用" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "846c3939b1f07c52",
  },
  {
    goalKinds: ["hiring"],
    id: "L-301",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "経済産業省「2024 年版 中小企業白書・小規模企業白書」公表", publishedOn: "2024-05-10", url: "https://www.meti.go.jp/press/2024/05/20240510002/20240510002.html" },
    status: "published",
    summary: {
      en: "The 2024 SME White Paper finds that small firms' sales have recovered from the pandemic dip, while labour shortages have become serious.",
      ja: "2024 年版の中小企業白書では、中小企業の売上は感染症の落ち込みから回復した一方、人手不足が深刻になっていると整理されています。",
      zh: "2024 年版《中小企业白皮书》指出，中小企业销售已从疫情低谷回升，但人手不足日益严重。",
    },
    title: { en: "Labour shortages at small firms (2024 white paper)", ja: "中小企業の人手不足（2024 年白書）", zh: "中小企业人手不足（2024 年白皮书）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "730f5e1f8b4c0013",
  },
  {
    goalKinds: ["hiring", "career"],
    id: "L-401",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "厚生労働省「一般職業紹介状況（令和 7 年 12 月分及び令和 7 年分）」", publishedOn: "2026-01-30", url: "https://www.mhlw.go.jp/stf/newpage_69302.html" },
    status: "published",
    summary: {
      en: "At Japan's public employment offices (Hello Work), the 2025 average ratio of job openings to applicants was 1.22.",
      ja: "ハローワークにおける 2025 年平均の有効求人倍率は 1.22 倍でした。",
      zh: "公共职业介绍所（Hello Work）统计的 2025 年平均有效求人倍率为 1.22 倍。",
    },
    title: { en: "Jobs-to-applicants ratio, 2025", ja: "有効求人倍率（2025 年平均）", zh: "有效求人倍率（2025 年平均）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "cb6568641c04fbb4",
  },
  {
    goalKinds: ["hiring", "career"],
    id: "L-402",
    industries: ["technology_internet"],
    reviewedBy: null,
    source: { label: "経済産業省（委託調査）「IT 人材の最新動向と将来推計に関する調査結果」", publishedOn: "2016-06-10", url: "https://www.meti.go.jp/policy/it_policy/jinzai/27FY/ITjinzai_report_summary.pdf" },
    status: "draft",
    summary: {
      en: "A 2016 government-commissioned estimate projected a shortage of about 790,000 IT workers by 2030 under a high-growth scenario (a conditional projection, not a measured figure).",
      ja: "2016 年の試算では、需要が高く伸びるシナリオの場合、2030 年に IT 人材が約 79 万人不足するとされました（条件つきの推計で、実測値ではありません）。",
      zh: "2016 年的测算显示，在需求高速增长的情景下，2030 年 IT 人才将短缺约 79 万人（有前提条件的推算，不是实测值）。",
    },
    title: { en: "IT talent shortage (2016 estimate)", ja: "IT 人材の不足（2016 年の試算）", zh: "IT 人才短缺（2016 年测算）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "d4c6081e7089a39e",
  },
  {
    goalKinds: ["hiring"],
    id: "L-403",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "リクルートワークス研究所「中途採用実態調査（2025 年度実績、正規社員）」", publishedOn: "2026-06-12", url: "https://www.works-i.com/surveys/item/260612_midcareer.pdf" },
    status: "published",
    summary: {
      en: "Among private companies with 5 or more employees, 84.4% conducted or were conducting recruitment for regular mid-career staff in the second half of FY2025, the highest share since comparable data began in the second half of FY2013.",
      ja: "従業員 5 人以上の民間企業のうち、2025 年度下半期に正規社員の中途採用活動を「実施した・実施中」の企業は 84.4% で、比較できる 2013 年度下半期以降で最も高い割合でした。",
      zh: "员工 5 人以上的民营企业中，2025 年度下半年开展或正在开展正式员工社会招聘活动的企业占 84.4%，是可比的 2013 年度下半年以来最高。",
    },
    title: { en: "Share of firms hiring mid-career at a record", ja: "中途採用の実施企業割合が過去最高", zh: "进行社会招聘的企业比例创新高" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "26c5c6ac4713f688",
  },
  {
    goalKinds: ["partnership", "sales"],
    id: "L-502",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "NEDO「大企業等のスタートアップ連携・調達加速化事業」実施体制の決定", publishedOn: "2025-05-21", url: "https://www.nedo.go.jp/koubo/CA3_100487.html" },
    status: "published",
    summary: {
      en: "A public programme that helps large companies work with startups and buy their products and services began in FY2025.",
      ja: "大企業などがスタートアップと連携し、その製品やサービスを調達することを後押しする公的事業が、2025 年度に始まりました。",
      zh: "2025 年度启动了一项公共项目，支持大企业等与初创企业合作并采购其产品和服务。",
    },
    title: { en: "Public support for startup partnerships", ja: "大企業とスタートアップの連携を後押しする公的事業", zh: "推动大企业与初创企业合作的公共项目" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "120d9287779ff7e7",
  },
  {
    goalKinds: ["partnership", "sales"],
    id: "L-503",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "経済産業省「共創パートナーシップ 調達・購買ガイドライン」（概要版）", publishedOn: "2025-04-30", url: "https://www.meti.go.jp/policy/tech_promotion/partnership/guideline_summary.pdf" },
    status: "published",
    summary: {
      en: "A trade-ministry guideline (April 2025) sets out an \"initial purchase and validation\" stage: before full adoption, a company buys the products or services needed for validation and tests on site whether they solve the problem.",
      ja: "経済産業省のガイドラインは、事業会社がスタートアップと組むとき、本格導入の前に検証に必要な製品・サービスを購買し、現場で課題を解決できるか確かめる「初期購買・検証」の段階を示しています（2025 年 4 月）。",
      zh: "经济产业省的指南提出，企业与初创企业合作时，在正式引入前先采购验证所需的产品或服务，在业务现场验证能否解决课题（「初期采购·验证」阶段，2025 年 4 月）。",
    },
    title: { en: "Validate through an initial purchase", ja: "初期購買で製品・サービスを検証する", zh: "通过初期采购验证产品与服务" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "be03825c38b8d357",
  },
  {
    goalKinds: ["career"],
    id: "L-601",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "総務省「労働力調査（詳細集計）2025年（令和7年）10～12月期平均及び2025年（令和7年）平均」", publishedOn: "2026-02-13", url: "https://www.soumu.go.jp/menu_news/s-news/01toukei04_01000292.html" },
    status: "published",
    summary: {
      en: "On a 2025 annual average, 3.30 million employed people had changed jobs within the past year (10,000 fewer than the year before); 10.23 million wanted to change jobs or take on work in addition to their current job.",
      ja: "2025 年平均の転職者（就業中で、過去 1 年に仕事を変えた人）は 330 万人で、前年より 1 万人減りました。仕事を変えたい、または今の仕事に加えて別の仕事もしたい人は 1,023 万人です。",
      zh: "2025 年平均的跳槽者（在业且过去一年换过工作的人）为 330 万，比上年减少 1 万；想换工作或在现有工作之外再做一份工作的人有 1,023 万。",
    },
    title: { en: "Job changes in Japan, 2025", ja: "転職の動き（2025 年）", zh: "日本的跳槽情况（2025 年）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "b6b238050317c018",
  },
  {
    goalKinds: ["career", "launch"],
    id: "L-602",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "総務省統計局「令和 4 年 就業構造基本調査」", publishedOn: "2023-07-21", url: "https://www.stat.go.jp/data/shugyou/2022/index.html" },
    status: "published",
    summary: {
      en: "3.32 million people had a side job in 2022 (5.0% of workers), more than 40% up on 2012.",
      ja: "2022 年に副業がある人は 332 万人（有業者の 5.0%）で、2012 年から 4 割以上増えました。",
      zh: "2022 年有副业的人为 332 万（占就业者 5.0%），比 2012 年增加四成以上。",
    },
    title: { en: "Side jobs are growing", ja: "副業を持つ人の増加", zh: "有副业的人增多" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "006b405bd57ef215",
  },
  {
    goalKinds: ["career", "hiring"],
    id: "L-603",
    industries: [],
    reviewedBy: "features/plans/landscape/REVIEW.md",
    source: { label: "リクルートワークス研究所「新卒・中途採用横断レポート」", publishedOn: "2022-06-27", url: "https://www.works-i.com/surveys/item/220627_saiyou.pdf" },
    status: "published",
    summary: {
      en: "The survey found that in FY2012–2021, regular hiring at private companies in Japan was roughly 3 new graduates to 7 mid-career hires, and that large companies intended to raise the mid-career share over the medium to long term.",
      ja: "調査によると、2012〜2021 年度の民間企業の正規社員採用は、新卒と中途がおよそ 3 対 7 でした。大企業では、中長期的に中途の比率を高めたい意向も見られました。",
      zh: "调查显示，2012–2021 年度民营企业正式员工招聘中，应届与社招约为 3 比 7；大企业还有中长期提高社招比例的意向。",
    },
    title: { en: "Graduate vs mid-career hiring, FY2012–2021", ja: "正規社員採用の新卒・中途比率（2012〜2021 年度）", zh: "正式员工招聘的应届与社招比例（2012–2021 年度）" },
    updatedOn: "2026-10-10",
    version: 1,
    checksum: "9ebdc12d99369b8e",
  },
];
