export const ORBIT_KNOWLEDGE_MANIFEST = {
  "schemaVersion": 1,
  "generatedOn": "2026-06-30",
  "titleZh": "Orbit 知识库",
  "summaryZh": "这是 Orbit 项目的结构化知识入口。理解项目时，先读这里，再进入文档库、主题知识页、开发历史和排障经验，最后再阅读代码。",
  "documents": [
    {
      "id": "chat-agent-quality-loop-plan",
      "titleZh": "Chat Agent 质量循环计划",
      "summaryZh": "记录 Orbit Chat Agent 质量检查、trace 和改进循环的实施计划，是后续 agent 质量迭代的历史入口。",
      "reviewEvidenceZh": "已纳入历史计划类文档；当前实现状态应和 Orbit AI trace、chat API 和相关测试一起核对。",
      "sourcePath": "docs/superpowers/plans/2026-06-29-orbit-chat-agent-quality-loop.md",
      "category": "implementation-plan",
      "status": "historical",
      "freshness": "needs-code-check",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "orbit-ai-reference-redesign-sprints",
      "titleZh": "Orbit AI 参考重设计 Sprint",
      "summaryZh": "记录 Orbit AI 参考界面重设计的 sprint 拆分和验收方向，是 UI/agent 体验历史资料。",
      "reviewEvidenceZh": "已纳入历史设计类文档；当前 UI 以 app/(app)/app/orbit-ai* 和 dev trace 页面源码为准。",
      "sourcePath": "docs/superpowers/specs/2026-06-27-orbit-ai-reference-redesign-sprints.md",
      "category": "sprint-spec",
      "status": "historical",
      "freshness": "needs-code-check",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "harness-audit-2026-06-24",
      "titleZh": "Harness 审计 2026-06-24",
      "summaryZh": "记录长跑 harness 的早期审计结果、风险和修正方向，是理解 harness 演进的历史证据。",
      "reviewEvidenceZh": "已纳入历史审计；当前 harness 行为仍需以 harness/README、AGENT.md 和实际脚本为准。",
      "sourcePath": "harness-state/audits/2026-06-24-harness-audit.md",
      "category": "harness",
      "status": "historical",
      "freshness": "needs-code-check",
      "ownerArea": "harness"
    },
    {
      "id": "bootstrap-product-context",
      "titleZh": "Bootstrap 产品上下文",
      "summaryZh": "记录 harness 启动阶段使用的产品上下文，用于解释早期 sprint 为什么围绕 Orbit 关系管理和 mock capability 展开。",
      "reviewEvidenceZh": "已纳入历史上下文；当前产品方向应优先阅读 knowledge/wiki/project-overview.zh.md 和 docs/designs/inital_design.md。",
      "sourcePath": "harness-state/bootstrap-product-context.md",
      "category": "product-design",
      "status": "historical",
      "freshness": "needs-code-check",
      "ownerArea": "product"
    },
    {
      "id": "trace-debug-design-en",
      "titleZh": "Orbit AI Trace Debug 英文设计源",
      "summaryZh": "Orbit AI trace debug 设计的英文源文件；中文 companion 已在同目录保留，二者共同说明调试页面边界。",
      "reviewEvidenceZh": "已核对同目录存在中文 companion 和 /dev/orbit-ai/trace 页面；英文源保留为历史来源。",
      "sourcePath": "repos/orbits/docs/superpowers/specs/2026-06-29-orbit-ai-trace-debug-design.md",
      "category": "sprint-spec",
      "status": "historical",
      "freshness": "likely-current",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "orbits-app-readme",
      "titleZh": "Orbits App 开发 README",
      "summaryZh": "记录 Next.js app 的基础启动、开发命令和项目入口，是 repos/orbits 内最短的操作说明。",
      "reviewEvidenceZh": "已核对 package.json 中仍存在 README 提到的核心脚本；详细实现边界以 AGENTS.md 和知识库为准。",
      "sourcePath": "repos/orbits/README.md",
      "category": "developer-guide",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "repos/orbits"
    },
    {
      "id": "manual-acceptance-guide",
      "titleZh": "手动验收指南",
      "summaryZh": "记录 app 手动验收路径和检查点，适合在自动测试之外做产品表面回归。",
      "reviewEvidenceZh": "已核对文档仍在 app scripts 目录；具体路径是否完整需随页面路由变化持续更新。",
      "sourcePath": "repos/orbits/scripts/manual-acceptance.md",
      "category": "developer-guide",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "qa"
    },
    {
      "id": "root-agent-operating-notes",
      "titleZh": "根 Agent 运行规则",
      "summaryZh": "定义 harness、repos/orbits、参考项目、sprint 粒度、产品化策略和知识库维护规则。",
      "reviewEvidenceZh": "已登记关联代码路径：harness、repos/orbits。",
      "sourcePath": "AGENT.md",
      "category": "harness",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "root"
    },
    {
      "id": "app-agent-rules",
      "titleZh": "Orbits App Agent 规则",
      "summaryZh": "定义 app repo 内实现边界、mock/live 替换、产品 UI 与 contract 解耦，以及 /dev/knowledge manifest 规则。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/app、repos/orbits/features、repos/orbits/shared。",
      "sourcePath": "repos/orbits/AGENTS.md",
      "category": "technical-design",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "repos/orbits"
    },
    {
      "id": "product-design-current",
      "titleZh": "Orbit 产品设计",
      "summaryZh": "描述 Orbit 复杂版产品方向，是理解关系资产、人脉管理和 Agent 目标的产品来源。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/designs/inital_design.md",
      "category": "product-design",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "product"
    },
    {
      "id": "product-design-v0",
      "titleZh": "Orbit 产品设计 v0",
      "summaryZh": "早期产品设计版本，保留用于理解历史上下文，阅读时应和当前产品设计对照。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/designs/inital_design.v0.md",
      "category": "product-design",
      "status": "historical",
      "freshness": "needs-code-check",
      "ownerArea": "product"
    },
    {
      "id": "technical-design",
      "titleZh": "Orbit 技术设计",
      "summaryZh": "说明 mock-first、contract-first、模块拆分、Next.js App Router 和服务层边界。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/app、repos/orbits/features、repos/orbits/shared。",
      "sourcePath": "docs/designs/orbit_technical_design.md",
      "category": "technical-design",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "architecture"
    },
    {
      "id": "modular-design",
      "titleZh": "模块化与热拔插设计",
      "summaryZh": "当前 app 模块化原则文档，说明 service factory、mock/hybrid/live 和 route view-model 防腐层。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features、repos/orbits/shared/services/module-mode.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modular-design.md",
      "category": "architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "architecture"
    },
    {
      "id": "local-remote-database",
      "titleZh": "Local Remote Database 边界",
      "summaryZh": "说明 app 本地/远端数据库边界和 relationship schema。由于数据层近期变化频繁，需要持续代码核对。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/shared/local-remote-store/orbit-database.ts。",
      "sourcePath": "repos/orbits/docs/architecture/local-remote-database.md",
      "category": "architecture",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "data"
    },
    {
      "id": "orbit-ai-performance-check",
      "titleZh": "Orbit AI 性能检查",
      "summaryZh": "记录 2026-06-30 Orbit AI Agent 性能检查，作为优化历史和风险背景。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/orbit-ai。",
      "sourcePath": "repos/orbits/docs/architecture/orbit-ai-agent-performance-check-2026-06-30.md",
      "category": "architecture",
      "status": "historical",
      "freshness": "needs-code-check",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "module-account",
      "titleZh": "account 模块架构",
      "summaryZh": "说明 account 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/account/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/account.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:account"
    },
    {
      "id": "module-acquisition",
      "titleZh": "acquisition 模块架构",
      "summaryZh": "说明 acquisition 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/acquisition/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/acquisition.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:acquisition"
    },
    {
      "id": "module-agent",
      "titleZh": "agent 模块架构",
      "summaryZh": "说明 agent 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/agent/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/agent.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:agent"
    },
    {
      "id": "module-ai-provider",
      "titleZh": "ai-provider 模块架构",
      "summaryZh": "说明 ai-provider 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/shared/ai/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/ai-provider.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:ai-provider"
    },
    {
      "id": "module-analysis",
      "titleZh": "analysis 模块架构",
      "summaryZh": "说明 analysis 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/analysis/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/analysis.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:analysis"
    },
    {
      "id": "module-audit",
      "titleZh": "audit 模块架构",
      "summaryZh": "说明 audit 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/audit/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/audit.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:audit"
    },
    {
      "id": "module-bootstrap",
      "titleZh": "bootstrap 模块架构",
      "summaryZh": "说明 bootstrap 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/bootstrap/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/bootstrap.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:bootstrap"
    },
    {
      "id": "module-chat",
      "titleZh": "chat 模块架构",
      "summaryZh": "说明 chat 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/chat/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/chat.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:chat"
    },
    {
      "id": "module-connections",
      "titleZh": "connections 模块架构",
      "summaryZh": "说明 connections 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/connections/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/connections.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:connections"
    },
    {
      "id": "module-contacts",
      "titleZh": "contacts 模块架构",
      "summaryZh": "说明 contacts 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/contacts/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/contacts.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:contacts"
    },
    {
      "id": "module-dashboard",
      "titleZh": "dashboard 模块架构",
      "summaryZh": "说明 dashboard 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/dashboard/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/dashboard.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:dashboard"
    },
    {
      "id": "module-events",
      "titleZh": "events 模块架构",
      "summaryZh": "说明 events 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/events/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/events.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:events"
    },
    {
      "id": "module-followups",
      "titleZh": "followups 模块架构",
      "summaryZh": "说明 followups 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/followups/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/followups.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:followups"
    },
    {
      "id": "module-notifications",
      "titleZh": "notifications 模块架构",
      "summaryZh": "说明 notifications 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/notifications/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/notifications.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:notifications"
    },
    {
      "id": "module-orbit-ai",
      "titleZh": "orbit-ai 模块架构",
      "summaryZh": "说明 orbit-ai 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/orbit-ai/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/orbit-ai.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:orbit-ai"
    },
    {
      "id": "module-permissions",
      "titleZh": "permissions 模块架构",
      "summaryZh": "说明 permissions 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/permissions/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/permissions.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:permissions"
    },
    {
      "id": "module-profile",
      "titleZh": "profile 模块架构",
      "summaryZh": "说明 profile 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/profile/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/profile.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:profile"
    },
    {
      "id": "module-recommendations",
      "titleZh": "recommendations 模块架构",
      "summaryZh": "说明 recommendations 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/recommendations/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/recommendations.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:recommendations"
    },
    {
      "id": "module-search",
      "titleZh": "search 模块架构",
      "summaryZh": "说明 search 模块的定位、期望行为、Mock 行为和热拔插边界。字段和状态仍以对应 contract 文件为准。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/search/service-factory.ts。",
      "sourcePath": "repos/orbits/docs/architecture/modules/search.md",
      "category": "module-architecture",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "module:search"
    },
    {
      "id": "feature-account-design",
      "titleZh": "account Feature 设计",
      "summaryZh": "记录 account feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/account。",
      "sourcePath": "repos/orbits/features/account/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:account"
    },
    {
      "id": "feature-acquisition-design",
      "titleZh": "acquisition Feature 设计",
      "summaryZh": "记录 acquisition feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/acquisition。",
      "sourcePath": "repos/orbits/features/acquisition/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "feature-agent-design",
      "titleZh": "agent Feature 设计",
      "summaryZh": "记录 agent feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/agent。",
      "sourcePath": "repos/orbits/features/agent/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:agent"
    },
    {
      "id": "feature-analysis-design",
      "titleZh": "analysis Feature 设计",
      "summaryZh": "记录 analysis feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/analysis。",
      "sourcePath": "repos/orbits/features/analysis/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:analysis"
    },
    {
      "id": "feature-audit-design",
      "titleZh": "audit Feature 设计",
      "summaryZh": "记录 audit feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/audit。",
      "sourcePath": "repos/orbits/features/audit/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:audit"
    },
    {
      "id": "feature-bootstrap-design",
      "titleZh": "bootstrap Feature 设计",
      "summaryZh": "记录 bootstrap feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/bootstrap。",
      "sourcePath": "repos/orbits/features/bootstrap/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:bootstrap"
    },
    {
      "id": "feature-chat-design",
      "titleZh": "chat Feature 设计",
      "summaryZh": "记录 chat feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/chat。",
      "sourcePath": "repos/orbits/features/chat/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:chat"
    },
    {
      "id": "feature-connections-design",
      "titleZh": "connections Feature 设计",
      "summaryZh": "记录 connections feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/connections。",
      "sourcePath": "repos/orbits/features/connections/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:connections"
    },
    {
      "id": "feature-contacts-design",
      "titleZh": "contacts Feature 设计",
      "summaryZh": "记录 contacts feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/contacts。",
      "sourcePath": "repos/orbits/features/contacts/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:contacts"
    },
    {
      "id": "feature-dashboard-design",
      "titleZh": "dashboard Feature 设计",
      "summaryZh": "记录 dashboard feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/dashboard。",
      "sourcePath": "repos/orbits/features/dashboard/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:dashboard"
    },
    {
      "id": "feature-events-design",
      "titleZh": "events Feature 设计",
      "summaryZh": "记录 events feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/events。",
      "sourcePath": "repos/orbits/features/events/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:events"
    },
    {
      "id": "feature-followups-design",
      "titleZh": "followups Feature 设计",
      "summaryZh": "记录 followups feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/followups。",
      "sourcePath": "repos/orbits/features/followups/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:followups"
    },
    {
      "id": "feature-notifications-design",
      "titleZh": "notifications Feature 设计",
      "summaryZh": "记录 notifications feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/notifications。",
      "sourcePath": "repos/orbits/features/notifications/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:notifications"
    },
    {
      "id": "feature-orbit-ai-design",
      "titleZh": "orbit-ai Feature 设计",
      "summaryZh": "记录 orbit-ai feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/orbit-ai。",
      "sourcePath": "repos/orbits/features/orbit-ai/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:orbit-ai"
    },
    {
      "id": "feature-permissions-design",
      "titleZh": "permissions Feature 设计",
      "summaryZh": "记录 permissions feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/permissions。",
      "sourcePath": "repos/orbits/features/permissions/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:permissions"
    },
    {
      "id": "feature-profile-design",
      "titleZh": "profile Feature 设计",
      "summaryZh": "记录 profile feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/profile。",
      "sourcePath": "repos/orbits/features/profile/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:profile"
    },
    {
      "id": "feature-recommendations-design",
      "titleZh": "recommendations Feature 设计",
      "summaryZh": "记录 recommendations feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/recommendations。",
      "sourcePath": "repos/orbits/features/recommendations/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:recommendations"
    },
    {
      "id": "feature-search-design",
      "titleZh": "search Feature 设计",
      "summaryZh": "记录 search feature 的设计边界和 mock-first 实施方向，是模块文档之后的第二层阅读材料。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/search。",
      "sourcePath": "repos/orbits/features/search/DESIGN.md",
      "category": "feature-design",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "feature:search"
    },
    {
      "id": "capability-first-sprint-design",
      "titleZh": "Capability-first Sprint 设计",
      "summaryZh": "解释为什么早期 Orbit sprint 以能力边界而不是页面组件为中心。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/superpowers/specs/2026-06-24-capability-first-sprint-design.md",
      "category": "sprint-spec",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "harness"
    },
    {
      "id": "component-level-sprint-design",
      "titleZh": "Component-level Sprint 旧设计",
      "summaryZh": "早期组件级 sprint 设计，已被 capability-first 设计替代。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/superpowers/specs/2026-06-24-component-level-sprint-design.md",
      "category": "sprint-spec",
      "status": "superseded",
      "freshness": "known-stale",
      "ownerArea": "harness"
    },
    {
      "id": "orbit-product-chat-agent-design",
      "titleZh": "产品级 Chat Agent 设计",
      "summaryZh": "记录 Orbit 产品级 Chat Agent 的目标、边界和 agent 工作流判断。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/superpowers/specs/2026-06-29-orbit-product-chat-agent-design.md",
      "category": "sprint-spec",
      "status": "current",
      "freshness": "needs-code-check",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "bounded-react-tool-registry",
      "titleZh": "Bounded ReAct 工具注册设计",
      "summaryZh": "设计 Orbit AI bounded ReAct runtime、工具 registry、policy gate、确认边界和工具风险等级。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/features/orbit-ai/agent-tools/registry.ts。",
      "sourcePath": "docs/superpowers/specs/2026-06-30-orbit-bounded-react-tool-registry-design.md",
      "category": "sprint-spec",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "trace-tool-catalog-plan",
      "titleZh": "Orbit AI Trace 工具目录计划",
      "summaryZh": "实施 trace debug 页面展示工具 catalog 和中文规格说明的计划。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/app/dev/orbit-ai/trace、repos/orbits/features/orbit-ai。",
      "sourcePath": "docs/superpowers/plans/2026-06-30-orbit-ai-trace-tool-catalog.md",
      "category": "implementation-plan",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "knowledge-wiki-design",
      "titleZh": "文档库与知识库设计",
      "summaryZh": "本次知识库目标的设计文档，定义 knowledge 目录、catalog、开发历史、learnings 和 /dev/knowledge 页面。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/superpowers/specs/2026-06-30-orbit-docs-knowledge-wiki-design.md",
      "category": "sprint-spec",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "knowledge"
    },
    {
      "id": "knowledge-wiki-plan",
      "titleZh": "文档库与知识库实施计划",
      "summaryZh": "把知识库目标拆成可测试任务：骨架、catalog、app manifest、可视化页面和最终验证。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/superpowers/plans/2026-06-30-orbit-docs-knowledge-wiki.md",
      "category": "implementation-plan",
      "status": "current",
      "freshness": "verified-current",
      "ownerArea": "knowledge"
    },
    {
      "id": "hybrid-mockdata-handoff-design",
      "titleZh": "Hybrid Mockdata Handoff 设计",
      "summaryZh": "定义 relationship mockdata 如何生成 TypeScript fixture 并接入 hybrid local-remote database。",
      "reviewEvidenceZh": "已登记关联代码路径：harness/relationship_data_goal_runner.py、repos/orbits/shared/mock/fixtures.ts。",
      "sourcePath": "docs/superpowers/specs/2026-06-30-hybrid-mockdata-handoff-design.md",
      "category": "sprint-spec",
      "status": "current",
      "freshness": "needs-code-check",
      "ownerArea": "data"
    },
    {
      "id": "hybrid-mockdata-handoff-plan",
      "titleZh": "Hybrid Mockdata Handoff 计划",
      "summaryZh": "实施 generated relationship fixture 接入 app mock/hybrid 数据层的计划。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "docs/superpowers/plans/2026-06-30-hybrid-mockdata-handoff.md",
      "category": "implementation-plan",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "data"
    },
    {
      "id": "harness-readme",
      "titleZh": "Orbit 长跑 Harness README",
      "summaryZh": "说明 harness 架构、命令、运行证据和长跑开发流程，是 harness 操作的主要英文来源。",
      "reviewEvidenceZh": "已登记关联代码路径：harness。",
      "sourcePath": "harness/README.md",
      "category": "harness",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "harness"
    },
    {
      "id": "harness-state-spec",
      "titleZh": "Harness 执行规格摘要",
      "summaryZh": "当前 harness-state/spec 是执行摘要，不是 sprint 详细需求来源。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "harness-state/spec.md",
      "category": "harness",
      "status": "current",
      "freshness": "needs-code-check",
      "ownerArea": "harness"
    },
    {
      "id": "harness-sprints-index",
      "titleZh": "Harness Sprint 索引",
      "summaryZh": "人类可读 sprint 历史索引，具体成功标准仍以 contract JSON 为准。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "harness-state/sprints.md",
      "category": "harness",
      "status": "current",
      "freshness": "needs-code-check",
      "ownerArea": "harness"
    },
    {
      "id": "product-facing-sprints",
      "titleZh": "产品化 Sprint Backlog",
      "summaryZh": "记录 Sprint 68 后从 mock capability loop 转向 /app/** 产品表面的产品化 backlog。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "harness-state/productization-notes/product-facing-sprints.md",
      "category": "harness",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "product"
    },
    {
      "id": "mockdata-design",
      "titleZh": "Relationship Mockdata 设计",
      "summaryZh": "用于生成关系 mock 数据、AI 画像建模、活动场景和 demo 数据的长文档。",
      "reviewEvidenceZh": "已登记关联代码路径：harness/relationship_data_goal_runner.py、repos/mockdata。",
      "sourcePath": "repos/mockdata/orbit_mock_data_ai_relationship_design.md",
      "category": "mockdata",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "data"
    },
    {
      "id": "mockdata-generation-readme",
      "titleZh": "Mockdata 生成 README",
      "summaryZh": "说明 relationship mockdata 生成目录和运行方式，需要和当前 generator 代码保持同步。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/mockdata/generation、harness/relationship_data_goal_runner.py。",
      "sourcePath": "repos/mockdata/generation/README.md",
      "category": "mockdata",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "data"
    },
    {
      "id": "trace-debug-design",
      "titleZh": "Orbit AI Trace Debug 设计",
      "summaryZh": "设计 /dev/orbit-ai/trace 调试页面，用于观察 pipeline、trace、工具调用和运行快照。",
      "reviewEvidenceZh": "已登记关联代码路径：repos/orbits/app/dev/orbit-ai/trace。",
      "sourcePath": "repos/orbits/docs/superpowers/specs/2026-06-29-orbit-ai-trace-debug-design.zh.md",
      "category": "sprint-spec",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "trace-debug-plan",
      "titleZh": "Orbit AI Trace Debug 计划",
      "summaryZh": "实现 Orbit AI trace debug 页面和 API 的计划。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "repos/orbits/docs/superpowers/plans/2026-06-29-orbit-ai-trace-debug.md",
      "category": "implementation-plan",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "orbit-ai"
    },
    {
      "id": "mock-to-live-sprint-68",
      "titleZh": "Sprint 68 Mock-to-Live 交接文档",
      "summaryZh": "记录 capability-first framework mock mode 到 live implementation 的替换要求。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "repos/orbits/docs/mock-to-live/verify-that-the-capability-first-framework-can-run-the-mvp-loop-in-mock-mode-wit/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "architecture"
    },
    {
      "id": "learning-troubleshooting",
      "titleZh": "根排障知识",
      "summaryZh": "记录 Orbit AI trace submit loading、provider timeout 和 responsive submit 控件等排障过程。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": ".learnings/TROUBLESHOOTING.md",
      "category": "learning",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "learning"
    },
    {
      "id": "learning-errors",
      "titleZh": "根错误记录",
      "summaryZh": "记录 harness 依赖、tsx eval、provider hang 和 git diff 命令等错误经验。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": ".learnings/ERRORS.md",
      "category": "learning",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "learning"
    },
    {
      "id": "learning-patterns-root",
      "titleZh": "根通用经验",
      "summaryZh": "记录用户反馈、harness best practices 和项目维护经验。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": ".learnings/LEARNINGS.md",
      "category": "learning",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "learning"
    },
    {
      "id": "learning-performance",
      "titleZh": "性能经验",
      "summaryZh": "记录性能检查相关经验，作为后续优化和回归排查入口。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": ".learnings/PERFORMANCE.md",
      "category": "learning",
      "status": "needs-review",
      "freshness": "needs-code-check",
      "ownerArea": "learning"
    },
    {
      "id": "app-learning-errors",
      "titleZh": "App 错误记录",
      "summaryZh": "记录 repos/orbits 内 fixture migration、comment patch、git diff 正则等错误经验。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "repos/orbits/.learnings/ERRORS.md",
      "category": "learning",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "learning"
    },
    {
      "id": "app-learning-patterns",
      "titleZh": "App 经验记录",
      "summaryZh": "记录 framework/mock/live 解耦、提交范围检查和注释提交卫生等经验。",
      "reviewEvidenceZh": "已登记来源文档，后续变更通过 catalog 新鲜度状态追踪。",
      "sourcePath": "repos/orbits/.learnings/LEARNINGS.md",
      "category": "learning",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "learning"
    },
    {
      "id": "harness-prompt-planner",
      "titleZh": "长跑 Harness planner 提示词",
      "summaryZh": "定义长跑 harness 中 planner 角色的职责、输入输出和执行约束，是多代理循环的系统提示来源。",
      "reviewEvidenceZh": "已核对 prompt 文件仍在 harness/prompts 下；实际执行行为需要和 harness 调用代码及运行证据一起审计。",
      "sourcePath": "harness/prompts/planner.md",
      "category": "harness",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "harness"
    },
    {
      "id": "harness-prompt-generator",
      "titleZh": "长跑 Harness generator 提示词",
      "summaryZh": "定义长跑 harness 中 generator 角色的职责、输入输出和执行约束，是多代理循环的系统提示来源。",
      "reviewEvidenceZh": "已核对 prompt 文件仍在 harness/prompts 下；实际执行行为需要和 harness 调用代码及运行证据一起审计。",
      "sourcePath": "harness/prompts/generator.md",
      "category": "harness",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "harness"
    },
    {
      "id": "harness-prompt-evaluator",
      "titleZh": "长跑 Harness evaluator 提示词",
      "summaryZh": "定义长跑 harness 中 evaluator 角色的职责、输入输出和执行约束，是多代理循环的系统提示来源。",
      "reviewEvidenceZh": "已核对 prompt 文件仍在 harness/prompts 下；实际执行行为需要和 harness 调用代码及运行证据一起审计。",
      "sourcePath": "harness/prompts/evaluator.md",
      "category": "harness",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "harness"
    },
    {
      "id": "harness-prompt-verifier",
      "titleZh": "长跑 Harness verifier 提示词",
      "summaryZh": "定义长跑 harness 中 verifier 角色的职责、输入输出和执行约束，是多代理循环的系统提示来源。",
      "reviewEvidenceZh": "已核对 prompt 文件仍在 harness/prompts 下；实际执行行为需要和 harness 调用代码及运行证据一起审计。",
      "sourcePath": "harness/prompts/verifier.md",
      "category": "harness",
      "status": "current",
      "freshness": "likely-current",
      "ownerArea": "harness"
    },
    {
      "id": "live-handoff-app-app-app-agent-compose-app-agent-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：agent/compose app agent from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 agent/compose app agent from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/agent/compose-app-agent-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/agent/compose-app-agent-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-chat-compose-app-chat-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：chat/compose app chat from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 chat/compose app chat from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/chat/compose-app-chat-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/chat/compose-app-chat-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-contacts-compose-app-contacts-demo-contact-1-from-previously-approved-mock-first-capabili",
      "titleZh": "App 页面组合交接：contacts/compose app contacts demo contact 1 from previously approved mock first capabili",
      "summaryZh": "记录 app 路由 contacts/compose app contacts demo contact 1 from previously approved mock first capabili 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/contacts/compose-app-contacts-demo-contact-1-from-previously-approved-mock-first-capabili。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/contacts/compose-app-contacts-demo-contact-1-from-previously-approved-mock-first-capabili/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-contacts-compose-app-contacts-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：contacts/compose app contacts from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 contacts/compose app contacts from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/contacts/compose-app-contacts-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/contacts/compose-app-contacts-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-contacts-new-compose-app-contacts-new-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：contacts/new/compose app contacts new from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 contacts/new/compose app contacts new from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/contacts/new/compose-app-contacts-new-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/contacts/new/compose-app-contacts-new-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-dashboard-compose-app-dashboard-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：dashboard/compose app dashboard from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 dashboard/compose app dashboard from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/dashboard/compose-app-dashboard-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/dashboard/compose-app-dashboard-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-events-compose-app-events-demo-event-1-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：events/compose app events demo event 1 from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 events/compose app events demo event 1 from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/events/compose-app-events-demo-event-1-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/events/compose-app-events-demo-event-1-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-events-compose-app-events-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：events/compose app events from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 events/compose app events from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/events/compose-app-events-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/events/compose-app-events-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-followups-compose-app-followups-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：followups/compose app followups from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 followups/compose app followups from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/followups/compose-app-followups-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/followups/compose-app-followups-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-app-profile-compose-app-profile-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：profile/compose app profile from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 profile/compose app profile from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/app/profile/compose-app-profile-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/app/profile/compose-app-profile-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-app-compose-app-from-previously-approved-mock-first-capabilities",
      "titleZh": "App 页面组合交接：(app)/compose app from previously approved mock first capabilities",
      "summaryZh": "记录 app 路由 (app)/compose app from previously approved mock first capabilities 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/(app)/compose-app-from-previously-approved-mock-first-capabilities。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/(app)/compose-app-from-previously-approved-mock-first-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-app-dev-capabilities-capability-debug-dashboard",
      "titleZh": "App 页面组合交接：dev/capabilities/capability debug dashboard",
      "summaryZh": "记录 app 路由 dev/capabilities/capability debug dashboard 如何由已批准的 mock-first capability 组合成可运行页面，以及未来 live 替换时需要保留的交互边界。",
      "reviewEvidenceZh": "已核对页面目录存在：repos/orbits/app/dev/capabilities/capability-debug-dashboard。页面是否仍完全匹配文档，需要结合 route view-model 和页面测试继续审计。",
      "sourcePath": "repos/orbits/app/dev/capabilities/capability-debug-dashboard/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "app"
    },
    {
      "id": "live-handoff-feature-account-mock-account-session",
      "titleZh": "account 能力 Live 交接：mock account session",
      "summaryZh": "记录 account 模块中 mock account session 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/account/mock-account-session。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/account/mock-account-session/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:account"
    },
    {
      "id": "live-handoff-feature-acquisition-business-card-review-and-confirm-flow",
      "titleZh": "acquisition 能力 Live 交接：business card review and confirm flow",
      "summaryZh": "记录 acquisition 模块中 business card review and confirm flow 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/business-card-review-and-confirm-flow。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/business-card-review-and-confirm-flow/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-business-card-scan-ocr-mock",
      "titleZh": "acquisition 能力 Live 交接：business card scan ocr mock",
      "summaryZh": "记录 acquisition 模块中 business card scan ocr mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/business-card-scan-ocr-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/business-card-scan-ocr-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-contact-acquisition-draft-pipeline",
      "titleZh": "acquisition 能力 Live 交接：contact acquisition draft pipeline",
      "summaryZh": "记录 acquisition 模块中 contact acquisition draft pipeline 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/contact-acquisition-draft-pipeline。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/contact-acquisition-draft-pipeline/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-duplicate-detection-and-merge-mock",
      "titleZh": "acquisition 能力 Live 交接：duplicate detection and merge mock",
      "summaryZh": "记录 acquisition 模块中 duplicate detection and merge mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/duplicate-detection-and-merge-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/duplicate-detection-and-merge-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-email-and-calendar-relationship-signal-mock",
      "titleZh": "acquisition 能力 Live 交接：email and calendar relationship signal mock",
      "summaryZh": "记录 acquisition 模块中 email and calendar relationship signal mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/email-and-calendar-relationship-signal-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/email-and-calendar-relationship-signal-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-event-attendee-import-mock",
      "titleZh": "acquisition 能力 Live 交接：event attendee import mock",
      "summaryZh": "记录 acquisition 模块中 event attendee import mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/event-attendee-import-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/event-attendee-import-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-external-contacts-import-mock",
      "titleZh": "acquisition 能力 Live 交接：external contacts import mock",
      "summaryZh": "记录 acquisition 模块中 external contacts import mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/external-contacts-import-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/external-contacts-import-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-manual-contact-creation-mock",
      "titleZh": "acquisition 能力 Live 交接：manual contact creation mock",
      "summaryZh": "记录 acquisition 模块中 manual contact creation mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/manual-contact-creation-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/manual-contact-creation-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-qr-scan-connect-mock",
      "titleZh": "acquisition 能力 Live 交接：qr scan connect mock",
      "summaryZh": "记录 acquisition 模块中 qr scan connect mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/qr-scan-connect-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/qr-scan-connect-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-acquisition-referral-and-recommended-contact-confirm-mock",
      "titleZh": "acquisition 能力 Live 交接：referral and recommended contact confirm mock",
      "summaryZh": "记录 acquisition 模块中 referral and recommended contact confirm mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/acquisition/referral-and-recommended-contact-confirm-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/acquisition/referral-and-recommended-contact-confirm-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:acquisition"
    },
    {
      "id": "live-handoff-feature-agent-agent-action-queue-mock",
      "titleZh": "agent 能力 Live 交接：agent action queue mock",
      "summaryZh": "记录 agent 模块中 agent action queue mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/agent/agent-action-queue-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/agent/agent-action-queue-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:agent"
    },
    {
      "id": "live-handoff-feature-agent-agent-autonomy-settings-mock",
      "titleZh": "agent 能力 Live 交接：agent autonomy settings mock",
      "summaryZh": "记录 agent 模块中 agent autonomy settings mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/agent/agent-autonomy-settings-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/agent/agent-autonomy-settings-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:agent"
    },
    {
      "id": "live-handoff-feature-agent-external-action-sandbox-mock",
      "titleZh": "agent 能力 Live 交接：external action sandbox mock",
      "summaryZh": "记录 agent 模块中 external action sandbox mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/agent/external-action-sandbox-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/agent/external-action-sandbox-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:agent"
    },
    {
      "id": "live-handoff-feature-analysis-relationship-value-scoring-mock",
      "titleZh": "analysis 能力 Live 交接：relationship value scoring mock",
      "summaryZh": "记录 analysis 模块中 relationship value scoring mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/analysis/relationship-value-scoring-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/analysis/relationship-value-scoring-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:analysis"
    },
    {
      "id": "live-handoff-feature-audit-source-consistency-and-provenance-audit",
      "titleZh": "audit 能力 Live 交接：source consistency and provenance audit",
      "summaryZh": "记录 audit 模块中 source consistency and provenance audit 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/audit/source-consistency-and-provenance-audit。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/audit/source-consistency-and-provenance-audit/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:audit"
    },
    {
      "id": "live-handoff-feature-bootstrap-app-bootstrap-mock-aggregator",
      "titleZh": "bootstrap 能力 Live 交接：app bootstrap mock aggregator",
      "summaryZh": "记录 bootstrap 模块中 app bootstrap mock aggregator 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/bootstrap/app-bootstrap-mock-aggregator。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/bootstrap/app-bootstrap-mock-aggregator/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:bootstrap"
    },
    {
      "id": "live-handoff-feature-chat-chat-conversation-and-message-mock",
      "titleZh": "chat 能力 Live 交接：chat conversation and message mock",
      "summaryZh": "记录 chat 模块中 chat conversation and message mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/chat/chat-conversation-and-message-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/chat/chat-conversation-and-message-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:chat"
    },
    {
      "id": "live-handoff-feature-chat-chat-privacy-controls-mock",
      "titleZh": "chat 能力 Live 交接：chat privacy controls mock",
      "summaryZh": "记录 chat 模块中 chat privacy controls mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/chat/chat-privacy-controls-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/chat/chat-privacy-controls-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:chat"
    },
    {
      "id": "live-handoff-feature-chat-chat-summary-and-extraction-mock",
      "titleZh": "chat 能力 Live 交接：chat summary and extraction mock",
      "summaryZh": "记录 chat 模块中 chat summary and extraction mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/chat/chat-summary-and-extraction-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/chat/chat-summary-and-extraction-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:chat"
    },
    {
      "id": "live-handoff-feature-chat-chat-writing-assist-mock",
      "titleZh": "chat 能力 Live 交接：chat writing assist mock",
      "summaryZh": "记录 chat 模块中 chat writing assist mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/chat/chat-writing-assist-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/chat/chat-writing-assist-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:chat"
    },
    {
      "id": "live-handoff-feature-connections-connection-and-evidence-service-mock",
      "titleZh": "connections 能力 Live 交接：connection and evidence service mock",
      "summaryZh": "记录 connections 模块中 connection and evidence service mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/connections/connection-and-evidence-service-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/connections/connection-and-evidence-service-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:connections"
    },
    {
      "id": "live-handoff-feature-connections-relationship-stage-and-profile-mock",
      "titleZh": "connections 能力 Live 交接：relationship stage and profile mock",
      "summaryZh": "记录 connections 模块中 relationship stage and profile mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/connections/relationship-stage-and-profile-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/connections/relationship-stage-and-profile-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:connections"
    },
    {
      "id": "live-handoff-feature-contacts-contact-detail-tag-and-status-mock",
      "titleZh": "contacts 能力 Live 交接：contact detail tag and status mock",
      "summaryZh": "记录 contacts 模块中 contact detail tag and status mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/contacts/contact-detail-tag-and-status-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/contacts/contact-detail-tag-and-status-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:contacts"
    },
    {
      "id": "live-handoff-feature-contacts-contacts-list-search-and-filter-mock",
      "titleZh": "contacts 能力 Live 交接：contacts list search and filter mock",
      "summaryZh": "记录 contacts 模块中 contacts list search and filter mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/contacts/contacts-list-search-and-filter-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/contacts/contacts-list-search-and-filter-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:contacts"
    },
    {
      "id": "live-handoff-feature-dashboard-dashboard-aggregate-mock",
      "titleZh": "dashboard 能力 Live 交接：dashboard aggregate mock",
      "summaryZh": "记录 dashboard 模块中 dashboard aggregate mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/dashboard/dashboard-aggregate-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/dashboard/dashboard-aggregate-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:dashboard"
    },
    {
      "id": "live-handoff-feature-dashboard-network-distribution-analytics-mock",
      "titleZh": "dashboard 能力 Live 交接：network distribution analytics mock",
      "summaryZh": "记录 dashboard 模块中 network distribution analytics mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/dashboard/network-distribution-analytics-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/dashboard/network-distribution-analytics-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:dashboard"
    },
    {
      "id": "live-handoff-feature-dashboard-opportunity-reminder-analytics-mock",
      "titleZh": "dashboard 能力 Live 交接：opportunity reminder analytics mock",
      "summaryZh": "记录 dashboard 模块中 opportunity reminder analytics mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/dashboard/opportunity-reminder-analytics-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/dashboard/opportunity-reminder-analytics-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:dashboard"
    },
    {
      "id": "live-handoff-feature-events-event-attendee-roster-mock",
      "titleZh": "events 能力 Live 交接：event attendee roster mock",
      "summaryZh": "记录 events 模块中 event attendee roster mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/events/event-attendee-roster-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/events/event-attendee-roster-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:events"
    },
    {
      "id": "live-handoff-feature-events-event-crud-and-import-mock",
      "titleZh": "events 能力 Live 交接：event crud and import mock",
      "summaryZh": "记录 events 模块中 event crud and import mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/events/event-crud-and-import-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/events/event-crud-and-import-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:events"
    },
    {
      "id": "live-handoff-feature-events-event-encounter-note-capture-mock",
      "titleZh": "events 能力 Live 交接：event encounter note capture mock",
      "summaryZh": "记录 events 模块中 event encounter note capture mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/events/event-encounter-note-capture-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/events/event-encounter-note-capture-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:events"
    },
    {
      "id": "live-handoff-feature-events-event-goal-and-readiness-mock",
      "titleZh": "events 能力 Live 交接：event goal and readiness mock",
      "summaryZh": "记录 events 模块中 event goal and readiness mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/events/event-goal-and-readiness-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/events/event-goal-and-readiness-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:events"
    },
    {
      "id": "live-handoff-feature-events-on-site-want-to-connect-mock",
      "titleZh": "events 能力 Live 交接：on site want to connect mock",
      "summaryZh": "记录 events 模块中 on site want to connect mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/events/on-site-want-to-connect-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/events/on-site-want-to-connect-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:events"
    },
    {
      "id": "live-handoff-feature-events-post-event-contact-review-mock",
      "titleZh": "events 能力 Live 交接：post event contact review mock",
      "summaryZh": "记录 events 模块中 post event contact review mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/events/post-event-contact-review-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/events/post-event-contact-review-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:events"
    },
    {
      "id": "live-handoff-feature-followups-followup-task-generation-mock",
      "titleZh": "followups 能力 Live 交接：followup task generation mock",
      "summaryZh": "记录 followups 模块中 followup task generation mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/followups/followup-task-generation-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/followups/followup-task-generation-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:followups"
    },
    {
      "id": "live-handoff-feature-followups-message-draft-generator-mock",
      "titleZh": "followups 能力 Live 交接：message draft generator mock",
      "summaryZh": "记录 followups 模块中 message draft generator mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/followups/message-draft-generator-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/followups/message-draft-generator-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:followups"
    },
    {
      "id": "live-handoff-feature-notifications-reminder-schedule-and-notification-mock",
      "titleZh": "notifications 能力 Live 交接：reminder schedule and notification mock",
      "summaryZh": "记录 notifications 模块中 reminder schedule and notification mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/notifications/reminder-schedule-and-notification-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/notifications/reminder-schedule-and-notification-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:notifications"
    },
    {
      "id": "live-handoff-feature-permissions-permission-state-and-staged-authorization-mock",
      "titleZh": "permissions 能力 Live 交接：permission state and staged authorization mock",
      "summaryZh": "记录 permissions 模块中 permission state and staged authorization mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/permissions/permission-state-and-staged-authorization-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/permissions/permission-state-and-staged-authorization-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:permissions"
    },
    {
      "id": "live-handoff-feature-permissions-sensitive-action-confirmation-guard",
      "titleZh": "permissions 能力 Live 交接：sensitive action confirmation guard",
      "summaryZh": "记录 permissions 模块中 sensitive action confirmation guard 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/permissions/sensitive-action-confirmation-guard。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/permissions/sensitive-action-confirmation-guard/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:permissions"
    },
    {
      "id": "live-handoff-feature-profile-profile-document-extraction-mock",
      "titleZh": "profile 能力 Live 交接：profile document extraction mock",
      "summaryZh": "记录 profile 模块中 profile document extraction mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/profile/profile-document-extraction-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/profile/profile-document-extraction-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:profile"
    },
    {
      "id": "live-handoff-feature-profile-profile-onboarding-and-manual-profile-editor",
      "titleZh": "profile 能力 Live 交接：profile onboarding and manual profile editor",
      "summaryZh": "记录 profile 模块中 profile onboarding and manual profile editor 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/profile/profile-onboarding-and-manual-profile-editor。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/profile/profile-onboarding-and-manual-profile-editor/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:profile"
    },
    {
      "id": "live-handoff-feature-profile-profile-signal-review-queue",
      "titleZh": "profile 能力 Live 交接：profile signal review queue",
      "summaryZh": "记录 profile 模块中 profile signal review queue 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/profile/profile-signal-review-queue。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/profile/profile-signal-review-queue/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:profile"
    },
    {
      "id": "live-handoff-feature-recommendations-event-recommendation-and-opening-line-mock",
      "titleZh": "recommendations 能力 Live 交接：event recommendation and opening line mock",
      "summaryZh": "记录 recommendations 模块中 event recommendation and opening line mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/recommendations/event-recommendation-and-opening-line-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/recommendations/event-recommendation-and-opening-line-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:recommendations"
    },
    {
      "id": "live-handoff-feature-recommendations-event-value-recommendation-mock",
      "titleZh": "recommendations 能力 Live 交接：event value recommendation mock",
      "summaryZh": "记录 recommendations 模块中 event value recommendation mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/recommendations/event-value-recommendation-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/recommendations/event-value-recommendation-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:recommendations"
    },
    {
      "id": "live-handoff-feature-search-relationship-natural-search-mock",
      "titleZh": "search 能力 Live 交接：relationship natural search mock",
      "summaryZh": "记录 search 模块中 relationship natural search mock 能力从 mock-first 实现切换到 live provider 时需要替换和验证的边界。",
      "reviewEvidenceZh": "已核对对应 feature 目录存在：repos/orbits/features/search/relationship-natural-search-mock。目录级实时行为仍以 service factory、API route 和测试为准。",
      "sourcePath": "repos/orbits/features/search/relationship-natural-search-mock/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "feature:search"
    },
    {
      "id": "live-handoff-shared-ai-ai-provider-mock-and-provenance-boundary",
      "titleZh": "Shared Runtime 交接：ai",
      "summaryZh": "记录 shared/ai 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/ai/ai-provider-mock-and-provenance-boundary。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/ai/ai-provider-mock-and-provenance-boundary/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:ai"
    },
    {
      "id": "live-handoff-shared-api-create-the-shared-api-and-runtime-mode-boundary-used-by-all-capabilities",
      "titleZh": "Shared Runtime 交接：api",
      "summaryZh": "记录 shared/api 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/api/create-the-shared-api-and-runtime-mode-boundary-used-by-all-capabilities。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/api/create-the-shared-api-and-runtime-mode-boundary-used-by-all-capabilities/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:api"
    },
    {
      "id": "live-handoff-shared-dev-app-scaffold",
      "titleZh": "Shared Runtime 交接：dev",
      "summaryZh": "记录 shared/dev 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/dev/app-scaffold。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/dev/app-scaffold/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:dev"
    },
    {
      "id": "live-handoff-shared-domain-create-the-shared-domain-contract-skeleton-before-capability-mocks",
      "titleZh": "Shared Runtime 交接：domain",
      "summaryZh": "记录 shared/domain 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/domain/create-the-shared-domain-contract-skeleton-before-capability-mocks。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/domain/create-the-shared-domain-contract-skeleton-before-capability-mocks/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:domain"
    },
    {
      "id": "live-handoff-shared-local-remote-store",
      "titleZh": "Shared Runtime 交接：local remote store",
      "summaryZh": "记录 shared/local-remote-store 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/local-remote-store。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/local-remote-store/RELATIONSHIP_SCHEMA_LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:local-remote-store"
    },
    {
      "id": "live-handoff-shared-mock-create-the-shared-mock-runtime-used-by-every-capability-sprint",
      "titleZh": "Shared Runtime 交接：mock",
      "summaryZh": "记录 shared/mock 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/mock/create-the-shared-mock-runtime-used-by-every-capability-sprint。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/mock/create-the-shared-mock-runtime-used-by-every-capability-sprint/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:mock"
    },
    {
      "id": "live-handoff-shared-mock-mock-data-mutation-reset-and-scenario-switcher",
      "titleZh": "Shared Runtime 交接：mock",
      "summaryZh": "记录 shared/mock 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/mock/mock-data-mutation-reset-and-scenario-switcher。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/mock/mock-data-mutation-reset-and-scenario-switcher/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:mock"
    },
    {
      "id": "live-handoff-shared-services-create-the-standard-way-pages-and-routes-obtain-mock-hybrid-or-live-services",
      "titleZh": "Shared Runtime 交接：services",
      "summaryZh": "记录 shared/services 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/services/create-the-standard-way-pages-and-routes-obtain-mock-hybrid-or-live-services。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/services/create-the-standard-way-pages-and-routes-obtain-mock-hybrid-or-live-services/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:services"
    },
    {
      "id": "live-handoff-shared-ui-app-shell",
      "titleZh": "Shared Runtime 交接：ui",
      "summaryZh": "记录 shared/ui 共享层从 mock 或本地实现迁移到 live/runtime provider 时的契约、替换点和验证要求。",
      "reviewEvidenceZh": "已核对共享代码目录存在：repos/orbits/shared/ui/app-shell。具体数据结构和 API 仍以 shared 层源码与测试为准。",
      "sourcePath": "repos/orbits/shared/ui/app-shell/LIVE_IMPLEMENTATION.md",
      "category": "implementation-handoff",
      "status": "generated-evidence",
      "freshness": "likely-current",
      "ownerArea": "shared:ui"
    }
  ],
  "topicPages": [
    {
      "id": "project-overview",
      "titleZh": "项目总览",
      "path": "knowledge/wiki/project-overview.zh.md",
      "summaryZh": "Orbit 是一个围绕关系资产、人脉上下文、活动场景、跟进任务和 Agent 辅助动作构建的 Next.js 应用。当前项目包含根 harness、生成应用 `repos/orbits`、mockdata 生成链路和大量设计/实施文档。"
    },
    {
      "id": "architecture",
      "titleZh": "架构总览",
      "path": "knowledge/wiki/architecture.zh.md",
      "summaryZh": "Orbit 的实现目标是模块化、可替换、可验证。页面、API、feature service、mock/hybrid/live provider 和测试各自有清晰边界。"
    },
    {
      "id": "agent-system",
      "titleZh": "Agent 系统",
      "path": "knowledge/wiki/agent-system.zh.md",
      "summaryZh": "Orbit Agent 由两个相关但不同的层组成：产品内的 Orbit AI / Agent 功能，以及根 harness 的多 agent 生成流程。"
    },
    {
      "id": "data-and-mockdata",
      "titleZh": "数据与 Mockdata",
      "path": "knowledge/wiki/data-and-mockdata.zh.md",
      "summaryZh": "Orbit 当前使用 mock-first 和 hybrid local-remote database 过渡真实数据层。目标是让 mock 数据、generated fixture 和未来 live provider 都映射到同一组 DTO。"
    },
    {
      "id": "harness",
      "titleZh": "Harness",
      "path": "knowledge/wiki/harness.zh.md",
      "summaryZh": "根目录 `harness/` 是 Orbit 长跑开发系统，负责计划、生成、评价、验证和证据归档。生成应用目标是 `repos/orbits`，参考项目 `repos/tokyo-business-connect` 只读。"
    },
    {
      "id": "modules",
      "titleZh": "模块地图",
      "path": "knowledge/wiki/modules.zh.md",
      "summaryZh": "Orbit app 按业务能力拆为 feature modules。每个模块应有 contract、service interface、service factory、mock/hybrid/live 实现边界，以及中文模块架构文档。"
    }
  ],
  "recentHistory": [
    {
      "id": "knowledge-catalog-full-coverage",
      "date": "2026-06-30",
      "titleZh": "文档库全量覆盖审计",
      "summaryZh": "将 catalog 扩展到 146 个条目，扫描范围内未纳入 Markdown 降为 0，并为每项加入中文审计依据。",
      "sourcePath": "knowledge/history/development-log.zh.md"
    },
    {
      "id": "knowledge-wiki-implementation",
      "date": "2026-06-30",
      "titleZh": "文档库与知识库第一版",
      "summaryZh": "建立 knowledge 骨架、文档 catalog、learnings 索引、app-local manifest 和 /dev/knowledge 页面。",
      "sourcePath": "knowledge/history/development-log.zh.md"
    },
    {
      "id": "knowledge-wiki-design",
      "date": "2026-06-30",
      "titleZh": "设计 Orbit 文档库与知识库",
      "summaryZh": "建立文档 catalog、知识库、开发历史、learnings 索引和 /dev/knowledge 页面目标。",
      "sourcePath": "knowledge/history/development-log.zh.md"
    }
  ],
  "learnings": [
    {
      "id": "troubleshooting",
      "titleZh": "排障知识",
      "summaryZh": "Orbit AI trace loading、provider timeout 和 responsive submit 控件经验。",
      "sourcePath": "knowledge/learnings/troubleshooting.zh.md"
    },
    {
      "id": "errors",
      "titleZh": "错误记录",
      "summaryZh": "依赖缺失、tsx eval、迁移脚本和 git diff 正则等错误记录。",
      "sourcePath": "knowledge/learnings/errors.zh.md"
    },
    {
      "id": "patterns",
      "titleZh": "复用模式",
      "summaryZh": "framework/mock/live 解耦、提交范围检查和注释提交卫生。",
      "sourcePath": "knowledge/learnings/patterns.zh.md"
    }
  ]
} as const;
